var Module = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da=import.meta.url,ea="",fa;try{ea=(new URL(".",da)).href}catch{}fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ha=console.log.bind(console),n=console.error.bind(console),ia,la,ma=!1,na,q,t,v,oa,w,y,pa,qa,ra,sa;
function ta(){var a=la.buffer;q=new Int8Array(a);v=new Int16Array(a);t=new Uint8Array(a);oa=new Uint16Array(a);w=new Int32Array(a);y=new Uint32Array(a);pa=new Float32Array(a);sa=new Float64Array(a);qa=new BigInt64Array(a);ra=new BigUint64Array(a)}var A=0,ua=null;function va(){A++;f.monitorRunDependencies?.(A)}function wa(){A--;f.monitorRunDependencies?.(A);if(0==A&&ua){var a=ua;ua=null;a()}}
function xa(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var ya;async function za(a){if(!ia)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==ya&&ia)a=new Uint8Array(ia);else throw"both async and sync fetching of the wasm failed";return a}async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),xa(d)}}
async function Ba(a){var b=ya;if(!ia&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return Aa(b,a)}class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Da=a=>{for(;0<a.length;)a.shift()(f)},Ea=[],Fa=[],Ga=()=>{var a=f.preRun.shift();Fa.push(a)},Ha=!0,B=()=>{var a=w[+Ia>>2];Ia+=4;return a},Ja=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},D=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ja(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ka=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},E=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],La=(a,b)=>D(a+"/"+b),Ma=()=>a=>crypto.getRandomValues(a),Na=a=>{(Na=Ma())(a)},Oa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:F.Qa();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ja(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Pa=(a,b)=>{function c(h){for(var k=0;k<h.length&&
""===h[k];k++);for(var l=h.length-1;0<=l&&""===h[l];l--);return k>l?[]:h.slice(k,l-k+1)}a=Oa(a).slice(1);b=Oa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Qa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,G=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Qa)return Qa.decode(a.subarray(b,c));for(d="";b<
c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=[],Sa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ta=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;
for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Ua=[];function Va(a,b){Ua[a]={input:[],output:[],sa:b};Wa(a,Xa)}
var Xa={open(a){var b=Ua[a.node.Va];if(!b)throw new F.R(43);a.X=b;a.seekable=!1},close(a){a.X.sa.Sa(a.X)},Sa(a){a.X.sa.Sa(a.X)},read(a,b,c,d){if(!a.X||!a.X.sa.mb)throw new F.R(60);for(var e=0,g=0;g<d;g++){try{var h=a.X.sa.mb(a.X)}catch(k){throw new F.R(29);}if(void 0===h&&0===e)throw new F.R(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.ta=Date.now());return e},write(a,b,c,d){if(!a.X||!a.X.sa.eb)throw new F.R(60);try{for(var e=0;e<d;e++)a.X.sa.eb(a.X,b[c+e])}catch(g){throw new F.R(29);
}d&&(a.node.ga=a.node.fa=Date.now());return e}},Ya={mb(){a:{if(!Ra.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Sa(a)+1);a=Ta(a,b,0,b.length);b.length=a;Ra=b}b=Ra.shift()}return b},eb(a,b){null===b||10===b?(ha(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},Sa(a){0<a.output?.length&&(ha(G(a.output)),a.output=[])},Kb(){return{cc:25856,ec:5,bc:191,dc:35387,ac:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Lb(){return 0},Mb(){return[24,80]}},Za={eb(a,b){null===b||10===b?(n(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},Sa(a){0<a.output?.length&&(n(G(a.output)),a.output=[])}},H={qa:null,Z(){return H.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=24576===(c&61440))||(e=4096===(c&61440));if(e)throw new F.R(63);H.qa||(H.qa={dir:{node:{ka:H.T.ka,ma:H.T.ma,Aa:H.T.Aa,ra:H.T.ra,Ma:H.T.Ma,Fa:H.T.Fa,Na:H.T.Na,La:H.T.La,xa:H.T.xa},stream:{ea:H.U.ea}},
file:{node:{ka:H.T.ka,ma:H.T.ma},stream:{ea:H.U.ea,read:H.U.read,write:H.U.write,Ea:H.U.Ea,Ja:H.U.Ja}},link:{node:{ka:H.T.ka,ma:H.T.ma,wa:H.T.wa},stream:{}},gb:{node:{ka:H.T.ka,ma:H.T.ma},stream:F.Ab}});c=F.createNode(a,b,c,d);I(c.mode)?(c.T=H.qa.dir.node,c.U=H.qa.dir.stream,c.V={}):F.isFile(c.mode)?(c.T=H.qa.file.node,c.U=H.qa.file.stream,c.aa=0,c.V=null):40960===(c.mode&61440)?(c.T=H.qa.link.node,c.U=H.qa.link.stream):8192===(c.mode&61440)&&(c.T=H.qa.gb.node,c.U=H.qa.gb.stream);c.ta=c.ga=c.fa=Date.now();
a&&(a.V[b]=c,a.ta=a.ga=a.fa=c.ta);return c},tc(a){return a.V?a.V.subarray?a.V.subarray(0,a.aa):new Uint8Array(a.V):new Uint8Array(0)},T:{ka(a){var b={};b.ic=8192===(a.mode&61440)?a.id:1;b.vc=a.id;b.mode=a.mode;b.Dc=1;b.uid=0;b.uc=0;b.Va=a.Va;I(a.mode)?b.size=4096:F.isFile(a.mode)?b.size=a.aa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ta=new Date(a.ta);b.ga=new Date(a.ga);b.fa=new Date(a.fa);b.xb=4096;b.yb=Math.ceil(b.size/b.xb);return b},ma(a,b){for(var c of["mode","atime","mtime","ctime"])null!=
b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.aa!=b&&(0==b?(a.V=null,a.aa=0):(c=a.V,a.V=new Uint8Array(b),c&&a.V.set(c.subarray(0,Math.min(b,a.aa))),a.aa=b)))},Aa(){throw H.kb;},ra(a,b,c,d){return H.createNode(a,b,c,d)},Ma(a,b,c){try{var d=K(b,c)}catch(g){}if(d){if(I(a.mode))for(var e in d.V)throw new F.R(55);$a(d)}delete a.parent.V[a.name];b.V[c]=a;a.name=c;b.fa=b.ga=a.parent.fa=a.parent.ga=Date.now()},Fa(a,b){delete a.V[b];a.fa=a.ga=Date.now()},Na(a,b){var c=K(a,b),d;for(d in c.V)throw new F.R(55);
delete a.V[b];a.fa=a.ga=Date.now()},La(a){return[".","..",...Object.keys(a.V)]},xa(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},wa(a){if(40960!==(a.mode&61440))throw new F.R(28);return a.link}},U:{read(a,b,c,d,e){var g=a.node.V;if(e>=a.node.aa)return 0;a=Math.min(a.node.aa-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===q.buffer&&(g=!1);if(!d)return 0;a=a.node;a.ga=a.fa=Date.now();if(b.subarray&&(!a.V||a.V.subarray)){if(g)return a.V=
b.subarray(c,c+d),a.aa=d;if(0===a.aa&&0===e)return a.V=b.slice(c,c+d),a.aa=d;if(e+d<=a.aa)return a.V.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.V?a.V.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.V,a.V=new Uint8Array(g),0<a.aa&&a.V.set(h.subarray(0,a.aa),0));if(a.V.subarray&&b.subarray)a.V.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.V[e+g]=b[c+g];a.aa=Math.max(a.aa,e+d);return d},ea(a,b,c){1===c?b+=a.position:2===c&&F.isFile(a.node.mode)&&(b+=a.node.aa);if(0>
b)throw new F.R(28);return b},Ea(a,b,c,d,e){if(!F.isFile(a.node.mode))throw new F.R(43);a=a.node.V;if(e&2||!a||a.buffer!==q.buffer){d=!0;xa();e=void 0;if(!e)throw new F.R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);q.set(a,e)}}else d=!1,e=a.byteOffset;return{Y:e,Xb:d}},Ja(a,b,c,d){H.U.write(a,b,0,d,c,!1);return 0}}},ab=async a=>{a=await fa(a);return new Uint8Array(a)},bb=[],db=(a,b,c,d)=>{"undefined"!=typeof Browser&&cb();var e=!1;bb.forEach(g=>
{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},fb=(a,b,c,d,e,g,h,k,l,m)=>{function p(z){function x(C){m?.();k||eb(a,b,C,d,e,l);g?.();wa(u)}db(z,r,x,()=>{h?.();wa(u)})||x(z)}var r=b?Oa(D(a+"/"+b)):a,u=`cp ${r}`;va(u);"string"==typeof c?ab(c).then(p,h):p(c)},gb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function cb(){var a,b,c;F.Ya=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?F.ua("/dev","stdin",a):F.xa("/dev/tty","/dev/stdin");b?F.ua("/dev","stdout",null,b):F.xa("/dev/tty","/dev/stdout");c?F.ua("/dev","stderr",null,c):F.xa("/dev/tty1","/dev/stderr");F.open("/dev/stdin",0);F.open("/dev/stdout",1);F.open("/dev/stderr",1)}function Wa(a,b){F.jb[a]={U:b}}function I(a){return 16384===(a&61440)}
function K(a,b){var c=I(a.mode)?(c=L(a,"x"))?c:a.T.Aa?0:2:54;if(c)throw new F.R(c);for(c=F.pa[hb(a.id,b)];c;c=c.Ca){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return F.Aa(a,b)}function $a(a){var b=hb(a.parent.id,a.name);if(F.pa[b]===a)F.pa[b]=a.Ca;else for(b=F.pa[b];b;){if(b.Ca===a){b.Ca=a.Ca;break}b=b.Ca}}
function eb(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:M(a),h=b?D(a+"/"+b):a);a=gb(d,e);h=F.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}kb(h,a|146);b=F.open(h,577);F.write(b,c,0,c.length,0,g);F.close(b);kb(h,a)}}
function N(a,b={}){if(!a)throw new F.R(44);b.Ra??(b.Ra=!0);"/"===a.charAt(0)||(a=F.Qa()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=F.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Ka(e),F.ab(d)){a=e+"/"+a.slice(g+1).join("/");continue a}else d=d.parent;else{e=D(e+"/"+a[g]);try{d=K(d,a[g])}catch(k){if(44===k?.oa&&h&&b.Pb)return{path:e};throw k;}!d.la||h&&!b.Ra||(d=d.la.root);if(40960===(d.mode&61440)&&(!h||b.ja)){if(!d.T.wa)throw new F.R(52);
d=d.T.wa(d);"/"===d.charAt(0)||(d=Ka(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new F.R(32);}function M(a){for(var b;;){if(F.ab(a))return a=a.Z.pb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%F.pa.length}function lb(a){var b=hb(a.parent.id,a.name);a.Ca=F.pa[b];F.pa[b]=a}
function mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function L(a,b){if(F.nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function nb(a,b){if(!I(a.mode))return 54;try{return K(a,b),20}catch(c){}return L(a,"wx")}
function ob(a,b,c){try{var d=K(a,b)}catch(e){return e.oa}if(a=L(a,"wx"))return a;if(c){if(!I(d.mode))return 54;if(F.ab(d)||M(d)===F.Qa())return 10}else if(I(d.mode))return 31;return 0}function pb(a,b){if(!a)throw new F.R(b);return a}function O(a){a=F.Ib(a);if(!a)throw new F.R(8);return a}function qb(a,b=-1){a=Object.assign(new F.vb,a);if(-1==b)a:{for(b=0;b<=F.wb;b++)if(!F.streams[b])break a;throw new F.R(33);}a.za=b;return F.streams[b]=a}
function rb(a,b,c){var d=a?.U.ma;a=d?a:b;d??=b.T.ma;pb(d,63);d(a,c)}function sb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Ia)}return b}function tb(a){var b={$b:4096,pc:4096,yb:1E6,Zb:5E5,Yb:5E5,files:F.cb,nc:F.cb-1,qc:42,flags:2,Cc:255};a.T.sb&&Object.assign(b,a.T.sb(a.Z.Qb.root));return b}function P(a,b=511){return F.ra(a,b&1023|16384,0)}function ub(a,b,c){"undefined"==typeof c&&(c=b,b=438);return F.ra(a,b|8192,c)}
function vb(a,b,c,d){rb(a,b,{mode:c&4095|b.mode&-4096,fa:Date.now(),lb:d})}function kb(a,b,c){a="string"==typeof a?N(a,{ja:!c}).node:a;vb(null,a,b,c)}function wb(a,b,c){if(I(b.mode))throw new F.R(31);if(!F.isFile(b.mode))throw new F.R(28);var d=L(b,"w");if(d)throw new F.R(d);rb(a,b,{size:c,timestamp:Date.now()})}function xb(a,b){a="string"==typeof a?a:M(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=D(a+"/"+c);try{P(d)}catch(e){if(20!=e.oa)throw e;}a=d}}return d}
function yb(a,b,c,d){a="string"==typeof a?a:M(a);b=D(a+"/"+b);return F.create(b,gb(c,d))}function zb(a){if(!(a.ob||a.Nb||a.link||a.V)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.V=(void 0)(a.url),a.aa=a.V.length}catch(b){throw new F.R(29);}}}
function Ab(a,b,c,d,e){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={ob:!1,url:c};var g=yb(a,b,d,e);c.V?g.V=c.V:c.url&&(g.V=null,g.url=c.url);Object.defineProperties(g,{aa:{get:function(){return this.V.length}}});var h={};Object.keys(g.U).forEach(k=>{var l=g.U[k];h[k]=(...m)=>{zb(g);return l(...m)}});h.read=(k,l,m,p,r)=>{zb(g);k=k.node.V;if(r>=k.length)l=0;else{p=Math.min(k.length-
r,p);if(k.slice)for(var u=0;u<p;u++)l[m+u]=k[r+u];else for(u=0;u<p;u++)l[m+u]=k.get(r+u);l=p}return l};h.Ea=()=>{zb(g);xa();throw new F.R(48);};g.U=h;return g}
var F={root:null,Ia:[],jb:{},streams:[],cb:1,pa:null,hb:"/",Ya:!1,nb:!0,Eb:null,Wa:0,rb:{},R:class{name="ErrnoError";constructor(a){this.oa=a}},vb:class{Pa={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Pa.flags}set flags(a){this.Pa.flags=a}get position(){return this.Pa.position}set position(a){this.Pa.position=a}},ub:class{T={};U={};la=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Z=a.Z;this.id=F.cb++;this.name=b;this.mode=c;this.Va=d;this.ta=
this.ga=this.fa=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Nb(){return I(this.mode)}get ob(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new F.ub(a,b,c,d);lb(a);return a},ab(a){return a===a.parent},isFile(a){return 32768===(a&61440)},wc(a){return 49152===(a&49152)},wb:4096,Ib:a=>F.streams[a],kc(a,b=-1){a=qb(a,b);a.U?.jc?.(a);return a},Ab:{open(a){a.U=
F.Gb(a.node.Va).U;a.U.open?.(a)},ea(){throw new F.R(70);}},bb:a=>a>>8,Ac:a=>a&255,Ba:(a,b)=>a<<8|b,Gb:a=>F.jb[a],tb(a,b){function c(h){F.Wa--;return b(h)}function d(h){if(h){if(!d.Db)return d.Db=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);F.Wa++;1<F.Wa&&n(`warning: ${F.Wa} FS.syncfs operations in flight at once, probably just doing extra work`);var e=sb(F.root.Z),g=0;e.forEach(h=>{if(!h.type.tb)return d(null);h.type.tb(h,a,d)})},Z(a,b,c){var d="/"===c;if(d&&F.root)throw new F.R(10);
if(!d&&c){var e=N(c,{Ra:!1});c=e.path;e=e.node;if(e.la)throw new F.R(10);if(!I(e.mode))throw new F.R(54);}b={type:a,Qb:b,pb:c,Ia:[]};a=a.Z(b);a.Z=b;b.root=a;d?F.root=a:e&&(e.la=b,e.Z&&e.Z.Ia.push(b));return a},Ic(a){a=N(a,{Ra:!1});if(!a.node.la)throw new F.R(28);a=a.node;var b=a.la,c=sb(b);Object.keys(F.pa).forEach(d=>{for(d=F.pa[d];d;){var e=d.Ca;c.includes(d.Z)&&$a(d);d=e}});a.la=null;a.Z.Ia.splice(a.Z.Ia.indexOf(b),1)},Aa(a,b){return a.T.Aa(a,b)},ra(a,b,c){var d=N(a,{parent:!0}).node;a=E(a);if(!a)throw new F.R(28);
if("."===a||".."===a)throw new F.R(20);var e=nb(d,a);if(e)throw new F.R(e);if(!d.T.ra)throw new F.R(63);return d.T.ra(d,a,b,c)},sb(a){return tb(N(a,{ja:!0}).node)},Gc(a){return tb(a.node)},create(a,b=438){return F.ra(a,b&4095|32768,0)},Bc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{P(d,b)}catch(g){if(20!=g.oa)throw g;}}},xa(a,b){if(!Oa(a))throw new F.R(44);var c=N(b,{parent:!0}).node;if(!c)throw new F.R(44);b=E(b);var d=nb(c,b);if(d)throw new F.R(d);if(!c.T.xa)throw new F.R(63);
return c.T.xa(c,b,a)},Ma(a,b){var c=Ka(a),d=Ka(b),e=E(a),g=E(b);var h=N(a,{parent:!0});var k=h.node;h=N(b,{parent:!0});h=h.node;if(!k||!h)throw new F.R(44);if(k.Z!==h.Z)throw new F.R(75);var l=K(k,e);a=Pa(a,d);if("."!==a.charAt(0))throw new F.R(28);a=Pa(b,c);if("."!==a.charAt(0))throw new F.R(55);try{var m=K(h,g)}catch(p){}if(l!==m){b=I(l.mode);if(e=ob(k,e,b))throw new F.R(e);if(e=m?ob(h,g,b):nb(h,g))throw new F.R(e);if(!k.T.Ma)throw new F.R(63);if(l.la||m&&m.la)throw new F.R(10);if(h!==k&&(e=L(k,
"w")))throw new F.R(e);$a(l);try{k.T.Ma(l,h,g),l.parent=h}catch(p){throw p;}finally{lb(l)}}},Na(a){var b=N(a,{parent:!0}).node;a=E(a);var c=K(b,a),d=ob(b,a,!0);if(d)throw new F.R(d);if(!b.T.Na)throw new F.R(63);if(c.la)throw new F.R(10);b.T.Na(b,a);$a(c)},La(a){a=N(a,{ja:!0}).node;return pb(a.T.La,54)(a)},Fa(a){var b=N(a,{parent:!0}).node;if(!b)throw new F.R(44);a=E(a);var c=K(b,a),d=ob(b,a,!1);if(d)throw new F.R(d);if(!b.T.Fa)throw new F.R(63);if(c.la)throw new F.R(10);b.T.Fa(b,a);$a(c)},wa(a){a=
N(a).node;if(!a)throw new F.R(44);if(!a.T.wa)throw new F.R(28);return a.T.wa(a)},stat(a,b){a=N(a,{ja:!b}).node;return pb(a.T.ka,63)(a)},rc(a){var b=O(a);a=b.node;var c=b.U.ka;b=c?b:a;c??=a.T.ka;pb(c,63);return c(b)},zc(a){return F.stat(a,!0)},xc(a,b){kb(a,b,!0)},lc(a,b){a=O(a);vb(a,a.node,b,!1)},yc(a){a="string"==typeof a?N(a,{ja:!1}).node:a;rb(null,a,{timestamp:Date.now(),lb:!0})},mc(a){a=O(a);rb(a,a.node,{timestamp:Date.now(),lb:!1})},truncate(a,b){if(0>b)throw new F.R(28);a="string"==typeof a?
N(a,{ja:!0}).node:a;wb(null,a,b)},sc(a,b){a=O(a);if(0>b||0===(a.flags&2097155))throw new F.R(28);wb(a,a.node,b)},Jc(a,b,c){a=N(a,{ja:!0}).node;pb(a.T.ma,63)(a,{ta:b,ga:c})},open(a,b,c=438){if(""===a)throw new F.R(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=N(a,{ja:!(b&131072),Pb:!0});d=a.node;a=a.path}var g=!1;if(b&
64)if(d){if(b&128)throw new F.R(20);}else{if(e)throw new F.R(31);d=F.ra(a,c|511,0);g=!0}if(!d)throw new F.R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!I(d.mode))throw new F.R(54);if(!g&&(e=d?40960===(d.mode&61440)?32:I(d.mode)&&("r"!==mb(b)||b&576)?31:L(d,mb(b)):44))throw new F.R(e);b&512&&!g&&F.truncate(d,0);b&=-131713;e=qb({node:d,path:M(d),flags:b,seekable:!0,position:0,U:d.U,Wb:[],error:!1});e.U.open&&e.U.open(e);g&&kb(d,c&511);!f.logReadFiles||b&1||a in F.rb||(F.rb[a]=1);return e},close(a){if(null===
a.za)throw new F.R(8);a.Xa&&(a.Xa=null);try{a.U.close&&a.U.close(a)}catch(b){throw b;}finally{F.streams[a.za]=null}a.za=null},ea(a,b,c){if(null===a.za)throw new F.R(8);if(!a.seekable||!a.U.ea)throw new F.R(70);if(0!=c&&1!=c&&2!=c)throw new F.R(28);a.position=a.U.ea(a,b,c);a.Wb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new F.R(28);if(null===a.za)throw new F.R(8);if(1===(a.flags&2097155))throw new F.R(8);if(I(a.node.mode))throw new F.R(31);if(!a.U.read)throw new F.R(28);var g="undefined"!=
typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F.R(70);b=a.U.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new F.R(28);if(null===a.za)throw new F.R(8);if(0===(a.flags&2097155))throw new F.R(8);if(I(a.node.mode))throw new F.R(31);if(!a.U.write)throw new F.R(28);a.seekable&&a.flags&1024&&F.ea(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new F.R(70);b=a.U.write(a,b,c,d,e,g);h||(a.position+=b);return b},Ea(a,b,c,d,e){if(0!==
(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new F.R(2);if(1===(a.flags&2097155))throw new F.R(2);if(!a.U.Ea)throw new F.R(43);if(!b)throw new F.R(28);return a.U.Ea(a,b,c,d,e)},Ja(a,b,c,d,e){return a.U.Ja?a.U.Ja(a,b,c,d,e):0},Za(a,b,c){if(!a.U.Za)throw new F.R(59);return a.U.Za(a,b,c)},Fc(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=F.open(a,b.flags);a=F.stat(a).size;var e=new Uint8Array(a);
F.read(d,e,0,a,0);"utf8"===b.encoding?c=G(e):"binary"===b.encoding&&(c=e);F.close(d);return c},Kc(a,b,c={}){c.flags=c.flags||577;a=F.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Sa(b)+1);b=Ta(b,d,0,d.length);F.write(a,d,0,b,void 0,c.zb)}else if(ArrayBuffer.isView(b))F.write(a,b,0,b.byteLength,void 0,c.zb);else throw Error("Unsupported data type");F.close(a)},Qa:()=>F.hb,fc(a){a=N(a,{ja:!0});if(null===a.node)throw new F.R(44);if(!I(a.node.mode))throw new F.R(54);var b=L(a.node,
"x");if(b)throw new F.R(b);F.hb=a.path},Ec(){F.Ya=!1;for(var a of F.streams)a&&F.close(a)},oc(a,b){try{var c=N(a,{ja:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=N(a,{parent:!0}),E(a),c=N(a,{ja:!b}),d=!0,e=c.node}catch(g){}return d?e:null},ua(a,b,c,d){a=La("string"==typeof a?a:M(a),b);b=gb(!!c,!!d);var e;(e=F.ua).bb??(e.bb=64);e=F.Ba(F.ua.bb++,0);Wa(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,l){for(var m=0,p=0;p<l;p++){try{var r=c()}catch(u){throw new F.R(29);}if(void 0===
r&&0===m)throw new F.R(6);if(null===r||void 0===r)break;m++;h[k+p]=r}m&&(g.node.ta=Date.now());return m},write(g,h,k,l){for(var m=0;m<l;m++)try{d(h[k+m])}catch(p){throw new F.R(29);}l&&(g.node.ga=g.node.fa=Date.now());return m}});return ub(a,b,e)}},Ia=void 0,Bb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Cb,Q=a=>{for(var b="";t[a];)b+=Cb[t[a++]];return b},Db={},R={},Eb={},S=f.BindingError=class extends Error{constructor(a){super(a);
this.name="BindingError"}},Fb=a=>{throw new S(a);};function Gb(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(R.hasOwnProperty(a)){if(c.Jb)return;throw new S(`Cannot register type '${d}' twice`);}R[a]=b;delete Eb[a];Db.hasOwnProperty(a)&&(b=Db[a],delete Db[a],b.forEach(e=>e()))}function T(a,b,c={}){return Gb(a,b,c)}
var Hb=(a,b,c)=>{switch(b){case 1:return c?d=>q[d]:d=>t[d];case 2:return c?d=>v[d>>1]:d=>oa[d>>1];case 4:return c?d=>w[d>>2]:d=>y[d>>2];case 8:return c?d=>qa[d>>3]:d=>ra[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ib=a=>{throw new S(a.S.$.W.name+" instance already deleted");},Jb=!1,Kb=()=>{},Lb=a=>{if("undefined"===typeof FinalizationRegistry)return Lb=b=>b,a;Jb=new FinalizationRegistry(b=>{b=b.S;--b.count.value;0===b.count.value&&(b.ca?b.ha.va(b.ca):b.$.W.va(b.Y))});
Lb=b=>{var c=b.S;c.ca&&Jb.register(b,{S:c},b);return b};Kb=b=>{Jb.unregister(b)};return Lb(a)},Mb=[];function Nb(){}
var Ob=(a,b)=>Object.defineProperty(b,"name",{value:a}),Pb={},Qb=(a,b,c)=>{if(void 0===a[b].ba){var d=a[b];a[b]=function(...e){if(!a[b].ba.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ba})!`);return a[b].ba[e.length].apply(this,e)};a[b].ba=[];a[b].ba[d.Ga]=d}},Rb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].ba&&void 0!==f[a].ba[c])throw new S(`Cannot register public name '${a}' twice`);Qb(f,
a,a);if(f[a].ba.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);f[a].ba[c]=b}else f[a]=b,f[a].Ga=c},Sb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Tb(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.Da=c;this.va=d;this.da=e;this.Fb=g;this.Oa=h;this.Cb=k;this.Sb=[]}
var Ub=(a,b,c)=>{for(;b!==c;){if(!b.Oa)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Oa(a);b=b.da}return a};function Vb(a,b){if(null===b){if(this.$a)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.S)throw new S(`Cannot pass "${Bb(b)}" as a ${this.name}`);if(!b.S.Y)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ub(b.S.Y,b.S.$.W,this.W)}
function Wb(a,b){if(null===b){if(this.$a)throw new S(`null is not a valid ${this.name}`);if(this.Ua){var c=this.Tb();null!==a&&a.push(this.va,c);return c}return 0}if(!b||!b.S)throw new S(`Cannot pass "${Bb(b)}" as a ${this.name}`);if(!b.S.Y)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Ta&&b.S.$.Ta)throw new S(`Cannot convert argument of type ${b.S.ha?b.S.ha.name:b.S.$.name} to parameter type ${this.name}`);c=Ub(b.S.Y,b.S.$.W,this.W);if(this.Ua){if(void 0===
b.S.ca)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Vb){case 0:if(b.S.ha===this)c=b.S.ca;else throw new S(`Cannot convert argument of type ${b.S.ha?b.S.ha.name:b.S.$.name} to parameter type ${this.name}`);break;case 1:c=b.S.ca;break;case 2:if(b.S.ha===this)c=b.S.ca;else{var d=b.clone();c=this.Ub(c,U(()=>d["delete"]()));null!==a&&a.push(this.va,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Xb(a,b){if(null===b){if(this.$a)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.S)throw new S(`Cannot pass "${Bb(b)}" as a ${this.name}`);if(!b.S.Y)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.S.$.Ta)throw new S(`Cannot convert argument of type ${b.S.$.name} to parameter type ${this.name}`);return Ub(b.S.Y,b.S.$.W,this.W)}function Yb(a){return this.fromWireType(y[a>>2])}
var Zb=(a,b,c)=>{if(b===c)return a;if(void 0===c.da)return null;a=Zb(a,b,c.da);return null===a?null:c.Cb(a)},$b={},ac=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.da;)b=a.Oa(b),a=a.da;return $b[b]},bc=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},cc=(a,b)=>{if(!b.$||!b.Y)throw new bc("makeClassHandle requires ptr and ptrType");if(!!b.ha!==!!b.ca)throw new bc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Lb(Object.create(a,
{S:{value:b,writable:!0}}))};function dc(a,b,c,d,e,g,h,k,l,m,p){this.name=a;this.W=b;this.$a=c;this.Ta=d;this.Ua=e;this.Rb=g;this.Vb=h;this.qb=k;this.Tb=l;this.Ub=m;this.va=p;e||void 0!==b.da?this.toWireType=Wb:(this.toWireType=d?Vb:Xb,this.ia=null)}
var fc=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new bc("Replacing nonexistent public symbol");void 0!==f[a].ba&&void 0!==c?f[a].ba[c]=b:(f[a]=b,f[a].Ga=c)},gc,V=(a,b)=>{a=Q(a);var c=gc.get(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class hc extends Error{}
var jc=a=>{a=ic(a);var b=Q(a);W(a);return b},kc=(a,b)=>{function c(g){e[g]||R[g]||(Eb[g]?Eb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new hc(`${a}: `+d.map(jc).join([", "]));},lc=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new bc("Mismatched type converter count");for(var l=0;l<a.length;++l)T(a[l],k[l])}a.forEach(k=>Eb[k]=b);var e=Array(b.length),g=[],h=0;b.forEach((k,l)=>{R.hasOwnProperty(k)?e[l]=R[k]:(g.push(k),Db.hasOwnProperty(k)||(Db[k]=[]),Db[k].push(()=>
{e[l]=R[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},mc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(y[b+4*d>>2]);return c},nc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function oc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ia)return!0;return!1}
function pc(a,b,c,d,e,g){var h=b.length;if(2>h)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=oc(b);c="void"!==b[0].name;d=[a,Fb,d,e,nc,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!l)for(e=k?1:2;e<b.length;++e)null!==b[e].ia&&d.push(b[e].ia);l=oc(b);e=b.length-2;var m=[],p=["fn"];k&&p.push("thisWired");for(h=0;h<e;++h)m.push(`arg${h}`),p.push(`arg${h}Wired`);m=m.join(",");p=p.join(",");m=`return function (${m}) {\n`;l&&
(m+="var destructors = [];\n");var r=l?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(m+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(h=0;h<e;++h)m+=`var arg${h}Wired = argType${h}['toWireType'](${r}, arg${h});\n`,u.push(`argType${h}`);m+=(c||g?"var rv = ":"")+`invoker(${p});\n`;if(l)m+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].ia&&(m+=`${g}_dtor(${g});\n`,
u.push(`${g}_dtor`));c&&(m+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [z,x]=[u,m+"}\n"];b=(new Function(...z,x))(...d);return Ob(a,b)}
var qc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},rc=[],X=[],sc=a=>{9<a&&0===--X[a+1]&&(X[a]=void 0,rc.push(a))},Y=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return X[a]},U=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=rc.pop()||X.length;X[b]=a;X[b+1]=1;return b}},tc={name:"emscripten::val",fromWireType:a=>{var b=Y(a);sc(a);return b},toWireType:(a,b)=>U(b),na:8,readValueFromPointer:Yb,ia:null},uc=
(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(pa[c>>2])};case 8:return function(c){return this.fromWireType(sa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},vc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,wc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&oa[c];)++c;c<<=1;if(32<c-a&&vc)return vc.decode(t.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=v[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},xc=(a,b,c)=>{c??=
2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)v[b>>1]=a.charCodeAt(e),b+=2;v[b>>1]=0;return b-d},yc=a=>2*a.length,zc=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=w[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Ac=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+
((g&1023)<<10)|h&1023}w[b>>2]=g;b+=4;if(b+4>c)break}w[b>>2]=0;return b-d},Bc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Cc=0,Dc=(a,b)=>{var c=R[a];if(void 0===c)throw a=`${b} has unknown type ${jc(a)}`,new S(a);return c},Ec=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(y[b>>2]=U(d));return a},Fc=[],Gc={},Hc=a=>{var b=Gc[a];return void 0===b?Q(a):b},Ic=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Jc=a=>{var b=Fc.length;
Fc.push(a);return b},Kc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Dc(y[b+4*d>>2],`parameter ${d}`);return c},Lc={},Mc=a=>{if(!(a instanceof Ca||"unwind"==a))throw a;},Nc=a=>{na=a;Ha||0<Cc||(f.onExit?.(a),ma=!0);throw new Ca(a);},Oc=a=>{if(!ma)try{if(a(),!(Ha||0<Cc))try{na=a=na,Nc(a)}catch(b){Mc(b)}}catch(b){Mc(b)}};F.hc=fb;F.pa=Array(4096);F.Z(H,{},"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");Wa(F.Ba(1,3),{read:()=>0,write:(d,e,g,h)=>h,ea:()=>0});ub("/dev/null",F.Ba(1,3));Va(F.Ba(5,0),Ya);Va(F.Ba(6,0),Za);ub("/dev/tty",F.Ba(5,0));ub("/dev/tty1",F.Ba(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Na(a),b=a.byteLength);return a[--b]};F.ua("/dev","random",c);F.ua("/dev","urandom",c);P("/dev/shm");P("/dev/shm/tmp")})();
(function(){P("/proc");var a=P("/proc/self");P("/proc/self/fd");F.Z({Z(){var b=F.createNode(a,"fd",16895,73);b.U={ea:H.U.ea};b.T={Aa(c,d){c=+d;var e=O(c);c={parent:null,Z:{pb:"fake"},T:{wa:()=>e.path},id:c+1};return c.parent=c},La(){return Array.from(F.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();F.Eb={MEMFS:H};H.kb=new F.R(44);H.kb.stack="<generic error, no stack>";for(var Pc=Array(256),Qc=0;256>Qc;++Qc)Pc[Qc]=String.fromCharCode(Qc);Cb=Pc;
(()=>{let a=Nb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Nb&&c instanceof Nb))return!1;var d=this.S.$.W,e=this.S.Y;c.S=c.S;var g=c.S.$.W;for(c=c.S.Y;d.da;)e=d.Oa(e),d=d.da;for(;g.da;)c=g.Oa(c),g=g.da;return d===g&&e===c},clone:function(){this.S.Y||Ib(this);if(this.S.Ka)return this.S.count.value+=1,this;var c=Lb,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.S;c=c(e.call(d,g,{S:{value:{count:h.count,Ha:h.Ha,Ka:h.Ka,Y:h.Y,$:h.$,ca:h.ca,ha:h.ha}}}));c.S.count.value+=
1;c.S.Ha=!1;return c},["delete"](){this.S.Y||Ib(this);if(this.S.Ha&&!this.S.Ka)throw new S("Object already scheduled for deletion");Kb(this);var c=this.S;--c.count.value;0===c.count.value&&(c.ca?c.ha.va(c.ca):c.$.W.va(c.Y));this.S.Ka||(this.S.ca=void 0,this.S.Y=void 0)},isDeleted:function(){return!this.S.Y},deleteLater:function(){this.S.Y||Ib(this);if(this.S.Ha&&!this.S.Ka)throw new S("Object already scheduled for deletion");Mb.push(this);this.S.Ha=!0;return this}});const b=Symbol.dispose;b&&(a[b]=
a["delete"])})();
Object.assign(dc.prototype,{Hb(a){this.qb&&(a=this.qb(a));return a},ib(a){this.va?.(a)},na:8,readValueFromPointer:Yb,fromWireType:function(a){function b(){return this.Ua?cc(this.W.Da,{$:this.Rb,Y:c,ha:this,ca:a}):cc(this.W.Da,{$:this,Y:a})}var c=this.Hb(a);if(!c)return this.ib(a),null;var d=ac(this.W,c);if(void 0!==d){if(0===d.S.count.value)return d.S.Y=c,d.S.ca=a,d.clone();d=d.clone();this.ib(a);return d}d=this.W.Fb(c);d=Pb[d];if(!d)return b.call(this);d=this.Ta?d.Bb:d.pointerType;var e=Zb(c,this.W,
d.W);return null===e?b.call(this):this.Ua?cc(d.W.Da,{$:d,Y:e,ha:this,ca:a}):cc(d.W.Da,{$:d,Y:e})}});X.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>X.length/2-5-rc.length;f.noExitRuntime&&(Ha=f.noExitRuntime);f.preloadPlugins&&(bb=f.preloadPlugins);f.print&&(ha=f.print);f.printErr&&(n=f.printErr);f.wasmBinary&&(ia=f.wasmBinary);f.addRunDependency=va;f.removeRunDependency=wa;f.FS_createPreloadedFile=fb;f.FS_unlink=(...a)=>F.Fa(...a);f.FS_createPath=(...a)=>xb(...a);
f.FS_createDevice=(...a)=>F.ua(...a);f.FS=F;f.FS_createDataFile=(...a)=>eb(...a);f.FS_createLazyFile=(...a)=>Ab(...a);
var Tc={y:function(a,b,c){Ia=c;try{var d=O(a);switch(b){case 21509:return d.X?0:-59;case 21505:if(!d.X)return-59;if(d.X.sa.Kb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=B();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var g=0;32>g;g++)q[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.X?0:-59;case 21506:case 21507:case 21508:if(!d.X)return-59;if(d.X.sa.Lb)for(e=B(),a=[],g=0;32>g;g++)a.push(q[e+g+17]);return 0;case 21519:if(!d.X)return-59;
e=B();return w[e>>2]=0;case 21520:return d.X?-28:-59;case 21531:return e=B(),F.Za(d,b,e);case 21523:if(!d.X)return-59;d.X.sa.Mb&&(g=[24,80],e=B(),v[e>>1]=g[0],v[e+2>>1]=g[1]);return 0;case 21524:return d.X?0:-59;case 21515:return d.X?0:-59;default:return-28}}catch(h){if("undefined"==typeof F||"ErrnoError"!==h.name)throw h;return-h.oa}},z:function(a,b,c,d){Ia=d;try{b=b?G(t,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?F.Qa():O(a).path;if(0==e.length)throw new F.R(44);b=g+"/"+e}var h=d?
B():0;return F.open(b,c,h).za}catch(k){if("undefined"==typeof F||"ErrnoError"!==k.name)throw k;return-k.oa}},A:()=>xa(""),m:(a,b,c)=>{b=Q(b);T(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Bb(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},na:8,readValueFromPointer:Hb(b,c,-1==b.indexOf("u")),ia:null})},E:(a,b,c,d)=>{b=Q(b);T(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,
g){return g?c:d},na:8,readValueFromPointer:function(e){return this.fromWireType(t[e])},ia:null})},C:(a,b,c,d,e,g,h,k,l,m,p,r,u)=>{p=Q(p);g=V(e,g);k&&=V(h,k);m&&=V(l,m);u=V(r,u);var z=Sb(p);Rb(z,function(){kc(`Cannot construct ${p} due to unbound types`,[d])});lc([a,b,c],d?[d]:[],x=>{x=x[0];if(d){var C=x.W;var ja=C.Da}else ja=Nb.prototype;x=Ob(p,function(...ib){if(Object.getPrototypeOf(this)!==jb)throw new S(`Use 'new' to construct ${p}`);if(void 0===J.ya)throw new S(`${p} has no accessible constructor`);
var ec=J.ya[ib.length];if(void 0===ec)throw new S(`Tried to invoke ctor of ${p} with invalid number of parameters (${ib.length}) - expected (${Object.keys(J.ya).toString()}) parameters instead!`);return ec.apply(this,ib)});var jb=Object.create(ja,{constructor:{value:x}});x.prototype=jb;var J=new Tb(p,x,jb,u,C,g,k,m);if(J.da){var ka;(ka=J.da).fb??(ka.fb=[]);J.da.fb.push(J)}C=new dc(p,J,!0,!1,!1);ka=new dc(p+"*",J,!1,!1,!1);ja=new dc(p+" const*",J,!1,!0,!1);Pb[a]={pointerType:ka,Bb:ja};fc(z,x);return[C,
ka,ja]})},p:(a,b,c,d,e,g)=>{var h=mc(b,c);e=V(d,e);lc([],[a],k=>{k=k[0];var l=`constructor ${k.name}`;void 0===k.W.ya&&(k.W.ya=[]);if(void 0!==k.W.ya[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.W.ya[b-1]=()=>{kc(`Cannot construct ${k.name} due to unbound types`,h)};lc([],h,m=>{m.splice(1,0,null);k.W.ya[b-1]=pc(l,m,null,
e,g);return[]});return[]})},b:(a,b,c,d,e,g,h,k,l)=>{var m=mc(c,d);b=Q(b);b=qc(b);g=V(e,g);lc([],[a],p=>{function r(){kc(`Cannot call ${u} due to unbound types`,m)}p=p[0];var u=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&p.W.Sb.push(b);var z=p.W.Da,x=z[b];void 0===x||void 0===x.ba&&x.className!==p.name&&x.Ga===c-2?(r.Ga=c-2,r.className=p.name,z[b]=r):(Qb(z,b,u),z[b].ba[c-2]=r);lc([],m,C=>{C=pc(u,C,p,g,h,l);void 0===z[b].ba?(C.Ga=c-2,z[b]=C):z[b].ba[c-2]=C;return[]});return[]})},
B:a=>T(a,tc),l:(a,b,c)=>{b=Q(b);T(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,na:8,readValueFromPointer:uc(b,c),ia:null})},n:(a,b,c,d,e,g,h)=>{var k=mc(b,c);a=Q(a);a=qc(a);e=V(d,e);Rb(a,function(){kc(`Cannot call ${a} due to unbound types`,k)},b-1);lc([],k,l=>{fc(a,pc(a,[l[0],null].concat(l.slice(1)),null,e,g,h),b-1);return[]})},c:(a,b,c,d,e)=>{b=Q(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};
T(a,{name:b,fromWireType:e,toWireType:h,na:8,readValueFromPointer:Hb(b,c,0!==d),ia:null})},a:(a,b,c)=>{function d(g){return new e(q.buffer,y[g+4>>2],y[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c);T(a,{name:c,fromWireType:d,na:8,readValueFromPointer:d},{Jb:!0})},D:(a,b)=>{b=Q(b);T(a,{name:b,fromWireType:function(c){for(var d=y[c>>2],e=c+4,g,h=e,k=0;k<=d;++k){var l=e+k;if(k==d||0==t[l])h=h?G(t,h,l-
h):"",void 0===g?g=h:(g+=String.fromCharCode(0),g+=h),h=l+1}W(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var g=e?Sa(d):d.length;var h=Rc(4+g+1),k=h+4;y[h>>2]=g;e?Ta(d,t,k,g+1):t.set(d,k);null!==c&&c.push(W,h);return h},na:8,readValueFromPointer:Yb,ia(c){W(c)}})},f:(a,b,c)=>{c=Q(c);if(2===b){var d=wc;var e=xc;var g=yc;var h=
k=>oa[k>>1]}else 4===b&&(d=zc,e=Ac,g=Bc,h=k=>y[k>>2]);T(a,{name:c,fromWireType:k=>{for(var l=y[k>>2],m,p=k+4,r=0;r<=l;++r){var u=k+4+r*b;if(r==l||0==h(u))p=d(p,u-p),void 0===m?m=p:(m+=String.fromCharCode(0),m+=p),p=u+b}W(k);return m},toWireType:(k,l)=>{if("string"!=typeof l)throw new S(`Cannot pass non-string to C++ string type ${c}`);var m=g(l),p=Rc(4+m+b);y[p>>2]=m/b;e(l,p+4,m+b);null!==k&&k.push(W,p);return p},na:8,readValueFromPointer:Yb,ia(k){W(k)}})},h:a=>{T(a,tc)},F:(a,b)=>{b=Q(b);T(a,{Ob:!0,
name:b,na:0,fromWireType:()=>{},toWireType:()=>{}})},r:()=>{Ha=!1;Cc=0},g:(a,b,c)=>{a=Y(a);b=Dc(b,"emval::as");return Ec(b,c,a)},o:(a,b,c,d)=>{a=Fc[a];b=Y(b);return a(null,b,c,d)},G:(a,b,c,d,e)=>{a=Fc[a];b=Y(b);c=Hc(c);return a(b,b[c],d,e)},v:sc,H:a=>{if(0===a)return U(Ic());a=Hc(a);return U(Ic()[a])},i:(a,b,c)=>{b=Kc(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",g=0,h=[];0===c&&h.push("obj");for(var k=["retType"],l=[d],m=0;m<a;++m)h.push(`arg${m}`),k.push(`argType${m}`),
l.push(b[m]),e+=`  var arg${m} = argType${m}.readValueFromPointer(args${g?"+"+g:""});\n`,g+=b[m].na;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;d.Ob||(k.push("emval_returnValue"),l.push(Ec),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");a=(new Function(...k,e+"};\n"))(...l);c=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return Jc(Ob(c,a))},d:(a,b)=>{a=Y(a);b=Y(b);return U(a[b])},j:a=>{9<a&&(X[a+1]+=1)},I:a=>U(Hc(a)),J:a=>{var b=Y(a);nc(b);
sc(a)},e:(a,b)=>{a=Dc(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},s:(a,b)=>{Lc[a]&&(clearTimeout(Lc[a].id),delete Lc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Lc[a];Oc(()=>Sc(a,performance.now()))},b);Lc[a]={id:c,Hc:b};return 0},t:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-la.buffer.byteLength+65535)/65536|0;try{la.grow(d);ta();var e=1;
break a}catch(g){}e=void 0}if(e)return!0}return!1},k:function(a){try{var b=O(a);F.close(b);return 0}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return c.oa}},x:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=y[a>>2],l=y[a+4>>2];a+=8;var m=F.read(e,q,k,l,g);if(0>m){var p=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof g&&(g+=m)}p=b}y[d>>2]=p;return 0}catch(r){if("undefined"==typeof F||"ErrnoError"!==r.name)throw r;return r.oa}},u:function(a,b,c,d){b=-9007199254740992>
b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=O(a);F.ea(e,b,c);qa[d>>3]=BigInt(e.position);e.Xa&&0===b&&0===c&&(e.Xa=null);return 0}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return g.oa}},w:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=y[a>>2],l=y[a+4>>2];a+=8;var m=F.write(e,q,k,l,g);if(0>m){var p=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof g&&(g+=m)}p=b}y[d>>2]=p;return 0}catch(r){if("undefined"==typeof F||"ErrnoError"!==
r.name)throw r;return r.oa}},q:Nc},Z=await (async function(){function a(d){Z=d.exports;la=Z.K;ta();gc=Z.P;wa("wasm-instantiate");return Z}va("wasm-instantiate");var b={a:Tc};if(f.instantiateWasm)return new Promise(d=>{f.instantiateWasm(b,(e,g)=>{d(a(e,g))})});ya??=f.locateFile?f.locateFile?f.locateFile("thorvg.wasm",ea):ea+"thorvg.wasm":(new URL("thorvg.wasm",import.meta.url)).href;try{var c=await Ba(b);return a(c.instance)}catch(d){return ba(d),Promise.reject(d)}}()),W=Z.M,Rc=
Z.N,ic=Z.O,Sc=Z.Q;function Uc(){function a(){f.calledRun=!0;if(!ma){f.noFSInit||F.Ya||cb();Z.L();F.nb=!1;aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ea.push(b)}Da(Ea)}}if(0<A)ua=Uc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ga();Da(Fa);0<A?ua=Uc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();Uc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
