var Module = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(fa){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var ha=(a,b)=>{throw b;},ia=import.meta.url,ja="",ka,la;
if(fa){var fs=require("fs"),ma=require("path");ia.startsWith("file:")&&(ja=ma.dirname(require("url").fileURLToPath(ia))+"/");la=a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea){try{ja=(new URL(".",ia)).href}catch{}ea&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ka=async a=>
{if(na(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var oa=console.log.bind(console),n=console.error.bind(console),pa,qa,ra=!1,sa,r,t,y,ta,z,C,ua,va,wa,xa,na=a=>a.startsWith("file://");
function ya(){var a=qa.buffer;r=new Int8Array(a);y=new Int16Array(a);t=new Uint8Array(a);ta=new Uint16Array(a);z=new Int32Array(a);C=new Uint32Array(a);ua=new Float32Array(a);xa=new Float64Array(a);va=new BigInt64Array(a);wa=new BigUint64Array(a)}var D=0,za=null;function Aa(){D++;f.monitorRunDependencies?.(D)}function Ba(){D--;f.monitorRunDependencies?.(D);if(0==D&&za){var a=za;za=null;a()}}
function Ca(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Da;async function Ea(a){if(!pa)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==Da&&pa)a=new Uint8Array(pa);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Fa(a,b){try{var c=await Ea(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),Ca(d)}}async function Ga(a){var b=Da;if(!pa&&"function"==typeof WebAssembly.instantiateStreaming&&!na(b)&&!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return Fa(b,a)}
class Ha{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ia=a=>{for(;0<a.length;)a.shift()(f)},Ja=[],Ka=[],La=()=>{var a=f.preRun.shift();Ka.push(a)},Ma=!0,E=()=>{var a=z[+Na>>2];Na+=4;return a},Oa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Oa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},H=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Qa=(a,b)=>G(a+"/"+b),Ra=()=>{if(fa){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Sa=a=>{(Sa=Ra())(a)},Ta=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:I.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Oa(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Ua=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Ta(a).slice(1);b=Ta(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Va="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=
d);)++c;if(16<c-b&&a.buffer&&Va)return Va.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Wa=[],Xa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},Ya=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Za=a=>{var b=Array(Xa(a)+1);a=Ya(a,b,0,b.length);
b.length=a;return b},$a=[];function ab(a,b){$a[a]={input:[],output:[],ka:b};bb(a,cb)}
var cb={open(a){var b=$a[a.node.rdev];if(!b)throw new I.J(43);a.tty=b;a.seekable=!1},close(a){a.tty.ka.fsync(a.tty)},fsync(a){a.tty.ka.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ka.Wa)throw new I.J(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ka.Wa(a.tty)}catch(k){throw new I.J(29);}if(void 0===h&&0===e)throw new I.J(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ka.La)throw new I.J(60);try{for(var e=0;e<d;e++)a.tty.ka.La(a.tty,
b[c+e])}catch(g){throw new I.J(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},db={Wa(){a:{if(!Wa.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Wa=Za(a)}a=Wa.shift()}return a},La(a,b){null===b||10===
b?(oa(J(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(oa(J(a.output)),a.output=[])},sb(){return{Lb:25856,Nb:5,Kb:191,Mb:35387,Jb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},tb(){return 0},ub(){return[24,80]}},eb={La(a,b){null===b||10===b?(n(J(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(n(J(a.output)),a.output=[])}},K={ga:null,R(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||I.isFIFO(c))throw new I.J(63);K.ga||(K.ga={dir:{node:{aa:K.L.aa,da:K.L.da,lookup:K.L.lookup,ja:K.L.ja,rename:K.L.rename,unlink:K.L.unlink,rmdir:K.L.rmdir,readdir:K.L.readdir,symlink:K.L.symlink},stream:{X:K.M.X}},file:{node:{aa:K.L.aa,da:K.L.da},stream:{X:K.M.X,read:K.M.read,write:K.M.write,ra:K.M.ra,va:K.M.va}},link:{node:{aa:K.L.aa,da:K.L.da,readlink:K.L.readlink},stream:{}},Qa:{node:{aa:K.L.aa,da:K.L.da},stream:I.ib}});c=I.createNode(a,b,c,d);L(c.mode)?(c.L=K.ga.dir.node,c.M=K.ga.dir.stream,
c.N={}):I.isFile(c.mode)?(c.L=K.ga.file.node,c.M=K.ga.file.stream,c.T=0,c.N=null):40960===(c.mode&61440)?(c.L=K.ga.link.node,c.M=K.ga.link.stream):8192===(c.mode&61440)&&(c.L=K.ga.Qa.node,c.M=K.ga.Qa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.N[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Wb(a){return a.N?a.N.subarray?a.N.subarray(0,a.T):new Uint8Array(a.N):new Uint8Array(0)},L:{aa(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
L(a.mode)?b.size=4096:I.isFile(a.mode)?b.size=a.T:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},da(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.T!=b&&(0==b?(a.N=null,a.T=0):(c=a.N,a.N=new Uint8Array(b),c&&a.N.set(c.subarray(0,Math.min(b,a.T))),a.T=b)))},lookup(){throw K.Ua;},ja(a,b,c,d){return K.createNode(a,
b,c,d)},rename(a,b,c){try{var d=N(b,c)}catch(g){}if(d){if(L(a.mode))for(var e in d.N)throw new I.J(55);fb(d)}delete a.parent.N[a.name];b.N[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.N[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=N(a,b),d;for(d in c.N)throw new I.J(55);delete a.N[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.N)]},symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&
61440))throw new I.J(28);return a.link}},M:{read(a,b,c,d,e){var g=a.node.N;if(e>=a.node.T)return 0;a=Math.min(a.node.T-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===r.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.N||a.N.subarray)){if(g)return a.N=b.subarray(c,c+d),a.T=d;if(0===a.T&&0===e)return a.N=b.slice(c,c+d),a.T=d;if(e+d<=a.T)return a.N.set(b.subarray(c,c+d),e),d}g=e+d;var h=
a.N?a.N.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.N,a.N=new Uint8Array(g),0<a.T&&a.N.set(h.subarray(0,a.T),0));if(a.N.subarray&&b.subarray)a.N.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.N[e+g]=b[c+g];a.T=Math.max(a.T,e+d);return d},X(a,b,c){1===c?b+=a.position:2===c&&I.isFile(a.node.mode)&&(b+=a.node.T);if(0>b)throw new I.J(28);return b},ra(a,b,c,d,e){if(!I.isFile(a.node.mode))throw new I.J(43);a=a.node.N;if(e&2||!a||a.buffer!==r.buffer){d=!0;Ca();
e=void 0;if(!e)throw new I.J(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{P:e,Fb:d}},va(a,b,c,d){K.M.write(a,b,0,d,c,!1);return 0}}},gb=async a=>{a=await ka(a);return new Uint8Array(a)},hb=[],jb=(a,b,c,d)=>{"undefined"!=typeof Browser&&ib();var e=!1;hb.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},lb=(a,b,c,d,e,g,h,k,m,p)=>{function l(x){function u(w){p?.();k||kb(a,b,w,d,e,m);
g?.();Ba(v)}jb(x,q,u,()=>{h?.();Ba(v)})||u(x)}var q=b?Ta(G(a+"/"+b)):a,v=`cp ${q}`;Aa(v);"string"==typeof c?gb(c).then(l,h):l(c)},mb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function ib(){var a,b,c;I.Fa=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?I.la("/dev","stdin",a):I.symlink("/dev/tty","/dev/stdin");b?I.la("/dev","stdout",null,b):I.symlink("/dev/tty","/dev/stdout");c?I.la("/dev","stderr",null,c):I.symlink("/dev/tty1","/dev/stderr");I.open("/dev/stdin",0);I.open("/dev/stdout",1);I.open("/dev/stderr",1)}function bb(a,b){I.Ta[a]={M:b}}function L(a){return 16384===(a&61440)}
function N(a,b){var c=L(a.mode)?(c=O(a,"x"))?c:a.L.lookup?0:2:54;if(c)throw new I.J(c);for(c=I.fa[nb(a.id,b)];c;c=c.pa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return I.lookup(a,b)}function fb(a){var b=nb(a.parent.id,a.name);if(I.fa[b]===a)I.fa[b]=a.pa;else for(b=I.fa[b];b;){if(b.pa===a){b.pa=a.pa;break}b=b.pa}}
function kb(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:ob(a),h=b?G(a+"/"+b):a);a=mb(d,e);h=I.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}I.chmod(h,a|146);b=I.open(h,577);I.write(b,c,0,c.length,0,g);I.close(b);I.chmod(h,a)}}
function P(a,b={}){if(!a)throw new I.J(44);b.ya??(b.ya=!0);"/"===a.charAt(0)||(a=I.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=I.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Pa(e),I.Ia(d)){a=e+"/"+a.slice(g+1).join("/");continue a}else d=d.parent;else{e=G(e+"/"+a[g]);try{d=N(d,a[g])}catch(k){if(44===k?.ea&&h&&b.xb)return{path:e};throw k;}!d.ba||h&&!b.ya||(d=d.ba.root);if(40960===(d.mode&61440)&&(!h||b.$)){if(!d.L.readlink)throw new I.J(52);
d=d.L.readlink(d);"/"===d.charAt(0)||(d=Pa(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new I.J(32);}function ob(a){for(var b;;){if(I.Ia(a))return a=a.R.Ya,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function nb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%I.fa.length}function pb(a){var b=nb(a.parent.id,a.name);a.pa=I.fa[b];I.fa[b]=a}
function qb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function O(a,b){if(I.Xa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function rb(a,b){if(!L(a.mode))return 54;try{return N(a,b),20}catch(c){}return O(a,"wx")}
function sb(a,b,c){try{var d=N(a,b)}catch(e){return e.ea}if(a=O(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(I.Ia(d)||ob(d)===I.cwd())return 10}else if(L(d.mode))return 31;return 0}function tb(a,b){if(!a)throw new I.J(b);return a}function Q(a){a=I.qb(a);if(!a)throw new I.J(8);return a}function ub(a,b=-1){a=Object.assign(new I.eb,a);if(-1==b)a:{for(b=0;b<=I.fb;b++)if(!I.streams[b])break a;throw new I.J(33);}a.fd=b;return I.streams[b]=a}
function vb(a,b,c){var d=a?.M.da;a=d?a:b;d??=b.L.da;tb(d,63);d(a,c)}function wb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.ua)}return b}function xb(a){var b={Ib:4096,Tb:4096,blocks:1E6,Hb:5E5,Gb:5E5,files:I.Ka,Rb:I.Ka-1,Ub:42,flags:2,$b:255};a.L.ab&&Object.assign(b,a.L.ab(a.R.yb.root));return b}function yb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return I.ja(a,b|8192,c)}function zb(a,b,c,d){vb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Va:d})}
function Ab(a,b,c){if(L(b.mode))throw new I.J(31);if(!I.isFile(b.mode))throw new I.J(28);var d=O(b,"w");if(d)throw new I.J(d);vb(a,b,{size:c,timestamp:Date.now()})}function Bb(a,b){a="string"==typeof a?a:ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{I.mkdir(d)}catch(e){if(20!=e.ea)throw e;}a=d}}return d}function Cb(a,b,c,d){a="string"==typeof a?a:ob(a);b=G(a+"/"+b);return I.create(b,mb(c,d))}
function Db(a){if(!(a.vb||a.wb||a.link||a.N)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.N=la(a.url),a.T=a.N.length}catch(b){throw new I.J(29);}}}
function Eb(a,b,c,d,e){class g{Da=!1;ha=[];Ca=void 0;Na=0;Ma=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.Ca(l/this.chunkSize|0)[q]}}gb(l){this.Ca=l}Oa(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),v,x=(v=l.getResponseHeader("Accept-Ranges"))&&"bytes"===v;l=(v=l.getResponseHeader("Content-Encoding"))&&"gzip"===
v;var u=1048576;x||(u=q);var w=this;w.gb(F=>{var M=F*u,A=(F+1)*u-1;A=Math.min(A,q-1);if("undefined"==typeof w.ha[F]){var U=w.ha;if(M>A)throw Error("invalid range ("+M+", "+A+") or no bytes requested!");if(A>q-1)throw Error("only "+q+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);q!==u&&B.setRequestHeader("Range","bytes="+M+"-"+A);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&
300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);M=void 0!==B.response?new Uint8Array(B.response||[]):Za(B.responseText||"");U[F]=M}if("undefined"==typeof w.ha[F])throw Error("doXHR failed!");return w.ha[F]});if(l||!q)u=q=1,u=q=this.Ca(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Na=q;this.Ma=u;this.Da=!0}get length(){this.Da||this.Oa();return this.Na}get chunkSize(){this.Da||this.Oa();return this.Ma}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var m=Cb(a,b,d,e);h?m.N=h:k&&(m.N=null,m.url=k);Object.defineProperties(m,{T:{get:function(){return this.N.length}}});var p={};Object.keys(m.M).forEach(l=>{var q=m.M[l];p[l]=(...v)=>{Db(m);return q(...v)}});p.read=(l,q,v,x,u)=>{Db(m);l=l.node.N;if(u>=l.length)q=0;else{x=Math.min(l.length-u,x);if(l.slice)for(var w=
0;w<x;w++)q[v+w]=l[u+w];else for(w=0;w<x;w++)q[v+w]=l.get(u+w);q=x}return q};p.ra=()=>{Db(m);Ca();throw new I.J(48);};m.M=p;return m}
var I={root:null,ua:[],Ta:{},streams:[],Ka:1,fa:null,Ra:"/",Fa:!1,Xa:!0,mb:null,Ba:0,$a:{},J:class{name="ErrnoError";constructor(a){this.ea=a}},eb:class{ha={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ha.flags}set flags(a){this.ha.flags=a}get position(){return this.ha.position}set position(a){this.ha.position=a}},cb:class{L={};M={};ba=null;constructor(a,b,c,d){a||=this;this.parent=a;this.R=a.R;this.id=I.Ka++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get wb(){return L(this.mode)}get vb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new I.cb(a,b,c,d);pb(a);return a},Ia(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},fb:4096,qb:a=>I.streams[a],Qb(a,
b=-1){a=ub(a,b);a.M?.Pb?.(a);return a},ib:{open(a){a.M=I.ob(a.node.rdev).M;a.M.open?.(a)},X(){throw new I.J(70);}},Ja:a=>a>>8,Yb:a=>a&255,oa:(a,b)=>a<<8|b,ob:a=>I.Ta[a],bb(a,b){function c(h){I.Ba--;return b(h)}function d(h){if(h){if(!d.lb)return d.lb=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);I.Ba++;1<I.Ba&&n(`warning: ${I.Ba} FS.syncfs operations in flight at once, probably just doing extra work`);var e=wb(I.root.R),g=0;e.forEach(h=>{if(!h.type.bb)return d(null);h.type.bb(h,
a,d)})},R(a,b,c){var d="/"===c;if(d&&I.root)throw new I.J(10);if(!d&&c){var e=P(c,{ya:!1});c=e.path;e=e.node;if(e.ba)throw new I.J(10);if(!L(e.mode))throw new I.J(54);}b={type:a,yb:b,Ya:c,ua:[]};a=a.R(b);a.R=b;b.root=a;d?I.root=a:e&&(e.ba=b,e.R&&e.R.ua.push(b));return a},dc(a){a=P(a,{ya:!1});if(!a.node.ba)throw new I.J(28);a=a.node;var b=a.ba,c=wb(b);Object.keys(I.fa).forEach(d=>{for(d=I.fa[d];d;){var e=d.pa;c.includes(d.R)&&fb(d);d=e}});a.ba=null;a.R.ua.splice(a.R.ua.indexOf(b),1)},lookup(a,b){return a.L.lookup(a,
b)},ja(a,b,c){var d=P(a,{parent:!0}).node;a=H(a);if(!a)throw new I.J(28);if("."===a||".."===a)throw new I.J(20);var e=rb(d,a);if(e)throw new I.J(e);if(!d.L.ja)throw new I.J(63);return d.L.ja(d,a,b,c)},ab(a){return xb(P(a,{$:!0}).node)},bc(a){return xb(a.node)},create(a,b=438){return I.ja(a,b&4095|32768,0)},mkdir(a,b=511){return I.ja(a,b&1023|16384,0)},Zb(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{I.mkdir(d,b)}catch(g){if(20!=g.ea)throw g;}}},symlink(a,
b){if(!Ta(a))throw new I.J(44);var c=P(b,{parent:!0}).node;if(!c)throw new I.J(44);b=H(b);var d=rb(c,b);if(d)throw new I.J(d);if(!c.L.symlink)throw new I.J(63);return c.L.symlink(c,b,a)},rename(a,b){var c=Pa(a),d=Pa(b),e=H(a),g=H(b);var h=P(a,{parent:!0});var k=h.node;h=P(b,{parent:!0});h=h.node;if(!k||!h)throw new I.J(44);if(k.R!==h.R)throw new I.J(75);var m=N(k,e);a=Ua(a,d);if("."!==a.charAt(0))throw new I.J(28);a=Ua(b,c);if("."!==a.charAt(0))throw new I.J(55);try{var p=N(h,g)}catch(l){}if(m!==
p){b=L(m.mode);if(e=sb(k,e,b))throw new I.J(e);if(e=p?sb(h,g,b):rb(h,g))throw new I.J(e);if(!k.L.rename)throw new I.J(63);if(m.ba||p&&p.ba)throw new I.J(10);if(h!==k&&(e=O(k,"w")))throw new I.J(e);fb(m);try{k.L.rename(m,h,g),m.parent=h}catch(l){throw l;}finally{pb(m)}}},rmdir(a){var b=P(a,{parent:!0}).node;a=H(a);var c=N(b,a),d=sb(b,a,!0);if(d)throw new I.J(d);if(!b.L.rmdir)throw new I.J(63);if(c.ba)throw new I.J(10);b.L.rmdir(b,a);fb(c)},readdir(a){a=P(a,{$:!0}).node;return tb(a.L.readdir,54)(a)},
unlink(a){var b=P(a,{parent:!0}).node;if(!b)throw new I.J(44);a=H(a);var c=N(b,a),d=sb(b,a,!1);if(d)throw new I.J(d);if(!b.L.unlink)throw new I.J(63);if(c.ba)throw new I.J(10);b.L.unlink(b,a);fb(c)},readlink(a){a=P(a).node;if(!a)throw new I.J(44);if(!a.L.readlink)throw new I.J(28);return a.L.readlink(a)},stat(a,b){a=P(a,{$:!b}).node;return tb(a.L.aa,63)(a)},fstat(a){var b=Q(a);a=b.node;var c=b.M.aa;b=c?b:a;c??=a.L.aa;tb(c,63);return c(b)},lstat(a){return I.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
P(a,{$:!c}).node:a;zb(null,a,b,c)},lchmod(a,b){I.chmod(a,b,!0)},fchmod(a,b){a=Q(a);zb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?P(a,{$:!d}).node:a;vb(null,a,{timestamp:Date.now(),Va:d})},lchown(a,b,c){I.chown(a,b,c,!0)},fchown(a){a=Q(a);vb(a,a.node,{timestamp:Date.now(),Va:!1})},truncate(a,b){if(0>b)throw new I.J(28);a="string"==typeof a?P(a,{$:!0}).node:a;Ab(null,a,b)},Vb(a,b){a=Q(a);if(0>b||0===(a.flags&2097155))throw new I.J(28);Ab(a,a.node,b)},ec(a,b,c){a=P(a,{$:!0}).node;tb(a.L.da,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new I.J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=P(a,{$:!(b&131072),xb:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new I.J(20);}else{if(e)throw new I.J(31);d=I.ja(a,c|511,0);g=!0}if(!d)throw new I.J(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!L(d.mode))throw new I.J(54);if(!g&&(e=d?40960===(d.mode&61440)?32:L(d.mode)&&("r"!==qb(b)||b&576)?31:O(d,qb(b)):44))throw new I.J(e);b&512&&!g&&I.truncate(d,0);b&=-131713;e=ub({node:d,path:ob(d),flags:b,seekable:!0,position:0,M:d.M,Eb:[],error:!1});e.M.open&&e.M.open(e);g&&I.chmod(d,c&511);!f.logReadFiles||b&1||a in I.$a||(I.$a[a]=1);return e},close(a){if(null===a.fd)throw new I.J(8);a.Ea&&(a.Ea=null);try{a.M.close&&a.M.close(a)}catch(b){throw b;}finally{I.streams[a.fd]=null}a.fd=null},
X(a,b,c){if(null===a.fd)throw new I.J(8);if(!a.seekable||!a.M.X)throw new I.J(70);if(0!=c&&1!=c&&2!=c)throw new I.J(28);a.position=a.M.X(a,b,c);a.Eb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new I.J(28);if(null===a.fd)throw new I.J(8);if(1===(a.flags&2097155))throw new I.J(8);if(L(a.node.mode))throw new I.J(31);if(!a.M.read)throw new I.J(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I.J(70);b=a.M.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,
b,c,d,e,g){if(0>d||0>e)throw new I.J(28);if(null===a.fd)throw new I.J(8);if(0===(a.flags&2097155))throw new I.J(8);if(L(a.node.mode))throw new I.J(31);if(!a.M.write)throw new I.J(28);a.seekable&&a.flags&1024&&I.X(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new I.J(70);b=a.M.write(a,b,c,d,e,g);h||(a.position+=b);return b},ra(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new I.J(2);if(1===(a.flags&2097155))throw new I.J(2);if(!a.M.ra)throw new I.J(43);
if(!b)throw new I.J(28);return a.M.ra(a,b,c,d,e)},va(a,b,c,d,e){return a.M.va?a.M.va(a,b,c,d,e):0},Ga(a,b,c){if(!a.M.Ga)throw new I.J(59);return a.M.Ga(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=I.open(a,b.flags);a=I.stat(a).size;var e=new Uint8Array(a);I.read(d,e,0,a,0);"utf8"===b.encoding?c=J(e):"binary"===b.encoding&&(c=e);I.close(d);return c},writeFile(a,
b,c={}){c.flags=c.flags||577;a=I.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Xa(b)+1);b=Ya(b,d,0,d.length);I.write(a,d,0,b,void 0,c.hb)}else if(ArrayBuffer.isView(b))I.write(a,b,0,b.byteLength,void 0,c.hb);else throw Error("Unsupported data type");I.close(a)},cwd:()=>I.Ra,chdir(a){a=P(a,{$:!0});if(null===a.node)throw new I.J(44);if(!L(a.node.mode))throw new I.J(54);var b=O(a.node,"x");if(b)throw new I.J(b);I.Ra=a.path},ac(){I.Fa=!1;for(var a of I.streams)a&&I.close(a)},Sb(a,
b){try{var c=P(a,{$:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=P(a,{parent:!0}),H(a),c=P(a,{$:!b}),d=!0,e=c.node}catch(g){}return d?e:null},la(a,b,c,d){a=Qa("string"==typeof a?a:ob(a),b);b=mb(!!c,!!d);var e;(e=I.la).Ja??(e.Ja=64);e=I.oa(I.la.Ja++,0);bb(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,m){for(var p=0,l=0;l<m;l++){try{var q=c()}catch(v){throw new I.J(29);}if(void 0===q&&0===p)throw new I.J(6);if(null===q||void 0===q)break;p++;h[k+l]=q}p&&(g.node.atime=Date.now());
return p},write(g,h,k,m){for(var p=0;p<m;p++)try{d(h[k+p])}catch(l){throw new I.J(29);}m&&(g.node.mtime=g.node.ctime=Date.now());return p}});return yb(a,b,e)}},Na=void 0,Fb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Gb,R=a=>{for(var b="";t[a];)b+=Gb[t[a++]];return b},Hb={},S={},Ib={},T=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}},Jb=a=>{throw new T(a);};
function Kb(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(S.hasOwnProperty(a)){if(c.rb)return;throw new T(`Cannot register type '${d}' twice`);}S[a]=b;delete Ib[a];Hb.hasOwnProperty(a)&&(b=Hb[a],delete Hb[a],b.forEach(e=>e()))}function V(a,b,c={}){return Kb(a,b,c)}
var Lb=(a,b,c)=>{switch(b){case 1:return c?d=>r[d]:d=>t[d];case 2:return c?d=>y[d>>1]:d=>ta[d>>1];case 4:return c?d=>z[d>>2]:d=>C[d>>2];case 8:return c?d=>va[d>>3]:d=>wa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Mb=a=>{throw new T(a.K.S.O.name+" instance already deleted");},Nb=!1,Ob=()=>{},Pb=a=>{if("undefined"===typeof FinalizationRegistry)return Pb=b=>b,a;Nb=new FinalizationRegistry(b=>{b=b.K;--b.count.value;0===b.count.value&&(b.V?b.Y.ma(b.V):b.S.O.ma(b.P))});Pb=
b=>{var c=b.K;c.V&&Nb.register(b,{K:c},b);return b};Ob=b=>{Nb.unregister(b)};return Pb(a)},Qb=[];function Rb(){}
var Sb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Tb={},Ub=(a,b,c)=>{if(void 0===a[b].U){var d=a[b];a[b]=function(...e){if(!a[b].U.hasOwnProperty(e.length))throw new T(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].U})!`);return a[b].U[e.length].apply(this,e)};a[b].U=[];a[b].U[d.sa]=d}},Vb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].U&&void 0!==f[a].U[c])throw new T(`Cannot register public name '${a}' twice`);Ub(f,a,a);if(f[a].U.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].U[c]=b}else f[a]=b,f[a].sa=c},Wb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Xb(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.qa=c;this.ma=d;this.W=e;this.nb=g;this.xa=h;this.kb=k;this.Ab=[]}var Yb=(a,b,c)=>{for(;b!==c;){if(!b.xa)throw new T(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.xa(a);b=b.W}return a};
function Zb(a,b){if(null===b){if(this.Ha)throw new T(`null is not a valid ${this.name}`);return 0}if(!b.K)throw new T(`Cannot pass "${Fb(b)}" as a ${this.name}`);if(!b.K.P)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);return Yb(b.K.P,b.K.S.O,this.O)}
function $b(a,b){if(null===b){if(this.Ha)throw new T(`null is not a valid ${this.name}`);if(this.Aa){var c=this.Bb();null!==a&&a.push(this.ma,c);return c}return 0}if(!b||!b.K)throw new T(`Cannot pass "${Fb(b)}" as a ${this.name}`);if(!b.K.P)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.za&&b.K.S.za)throw new T(`Cannot convert argument of type ${b.K.Y?b.K.Y.name:b.K.S.name} to parameter type ${this.name}`);c=Yb(b.K.P,b.K.S.O,this.O);if(this.Aa){if(void 0===b.K.V)throw new T("Passing raw pointer to smart pointer is illegal");
switch(this.Db){case 0:if(b.K.Y===this)c=b.K.V;else throw new T(`Cannot convert argument of type ${b.K.Y?b.K.Y.name:b.K.S.name} to parameter type ${this.name}`);break;case 1:c=b.K.V;break;case 2:if(b.K.Y===this)c=b.K.V;else{var d=b.clone();c=this.Cb(c,ac(()=>d["delete"]()));null!==a&&a.push(this.ma,c)}break;default:throw new T("Unsupporting sharing policy");}}return c}
function cc(a,b){if(null===b){if(this.Ha)throw new T(`null is not a valid ${this.name}`);return 0}if(!b.K)throw new T(`Cannot pass "${Fb(b)}" as a ${this.name}`);if(!b.K.P)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.K.S.za)throw new T(`Cannot convert argument of type ${b.K.S.name} to parameter type ${this.name}`);return Yb(b.K.P,b.K.S.O,this.O)}function dc(a){return this.fromWireType(C[a>>2])}
var ec=(a,b,c)=>{if(b===c)return a;if(void 0===c.W)return null;a=ec(a,b,c.W);return null===a?null:c.kb(a)},fc={},gc=(a,b)=>{if(void 0===b)throw new T("ptr should not be undefined");for(;a.W;)b=a.xa(b),a=a.W;return fc[b]},hc=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},ic=(a,b)=>{if(!b.S||!b.P)throw new hc("makeClassHandle requires ptr and ptrType");if(!!b.Y!==!!b.V)throw new hc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Pb(Object.create(a,
{K:{value:b,writable:!0}}))};function jc(a,b,c,d,e,g,h,k,m,p,l){this.name=a;this.O=b;this.Ha=c;this.za=d;this.Aa=e;this.zb=g;this.Db=h;this.Za=k;this.Bb=m;this.Cb=p;this.ma=l;e||void 0!==b.W?this.toWireType=$b:(this.toWireType=d?Zb:cc,this.Z=null)}
var kc=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new hc("Replacing nonexistent public symbol");void 0!==f[a].U&&void 0!==c?f[a].U[c]=b:(f[a]=b,f[a].sa=c)},lc,W=(a,b)=>{a=R(a);var c=lc.get(b);if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);return c};class mc extends Error{}
var oc=a=>{a=nc(a);var b=R(a);X(a);return b},pc=(a,b)=>{function c(g){e[g]||S[g]||(Ib[g]?Ib[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new mc(`${a}: `+d.map(oc).join([", "]));},qc=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new hc("Mismatched type converter count");for(var m=0;m<a.length;++m)V(a[m],k[m])}a.forEach(k=>Ib[k]=b);var e=Array(b.length),g=[],h=0;b.forEach((k,m)=>{S.hasOwnProperty(k)?e[m]=S[k]:(g.push(k),Hb.hasOwnProperty(k)||(Hb[k]=[]),Hb[k].push(()=>
{e[m]=S[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},rc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c},sc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function tc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Z)return!0;return!1}
function uc(a,b,c,d,e,g){var h=b.length;if(2>h)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=tc(b);c="void"!==b[0].name;d=[a,Jb,d,e,sc,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].Z&&d.push(b[e].Z);m=tc(b);e=b.length-2;var p=[],l=["fn"];k&&l.push("thisWired");for(h=0;h<e;++h)p.push(`arg${h}`),l.push(`arg${h}Wired`);p=p.join(",");l=l.join(",");p=`return function (${p}) {\n`;m&&
(p+="var destructors = [];\n");var q=m?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+=`var thisWired = classParam['toWireType'](${q}, this);\n`);for(h=0;h<e;++h)p+=`var arg${h}Wired = argType${h}['toWireType'](${q}, arg${h});\n`,v.push(`argType${h}`);p+=(c||g?"var rv = ":"")+`invoker(${l});\n`;if(m)p+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].Z&&(p+=`${g}_dtor(${g});\n`,
v.push(`${g}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,u]=[v,p+"}\n"];b=(new Function(...x,u))(...d);return Sb(a,b)}
var vc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},wc=[],Y=[],xc=a=>{9<a&&0===--Y[a+1]&&(Y[a]=void 0,wc.push(a))},ac=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=wc.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},yc={name:"emscripten::val",fromWireType:a=>{if(!a)throw new T(`Cannot use deleted val. handle = ${a}`);var b=Y[a];xc(a);return b},toWireType:(a,b)=>ac(b),ia:8,readValueFromPointer:dc,Z:null},zc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>
2])};case 8:return function(c){return this.fromWireType(xa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ac="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Bc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Ac)return Ac.decode(t.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=y[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Cc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=
0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Dc=a=>2*a.length,Ec=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=z[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Fc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}z[b>>2]=g;b+=4;if(b+4>c)break}z[b>>2]=0;return b-d},Gc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Hc=0,Ic={},Jc=a=>{sa=a;Ma||0<Hc||(f.onExit?.(a),ra=!0);ha(a,new Ha(a))},Kc=a=>{if(!ra)try{if(a(),!(Ma||0<Hc))try{sa=a=sa,Jc(a)}catch(b){b instanceof Ha||"unwind"==b||ha(1,b)}}catch(b){b instanceof Ha||"unwind"==b||ha(1,b)}};I.Ob=lb;I.fa=Array(4096);I.R(K,{},"/");I.mkdir("/tmp");I.mkdir("/home");I.mkdir("/home/web_user");
(function(){I.mkdir("/dev");bb(I.oa(1,3),{read:()=>0,write:(d,e,g,h)=>h,X:()=>0});yb("/dev/null",I.oa(1,3));ab(I.oa(5,0),db);ab(I.oa(6,0),eb);yb("/dev/tty",I.oa(5,0));yb("/dev/tty1",I.oa(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Sa(a),b=a.byteLength);return a[--b]};I.la("/dev","random",c);I.la("/dev","urandom",c);I.mkdir("/dev/shm");I.mkdir("/dev/shm/tmp")})();
(function(){I.mkdir("/proc");var a=I.mkdir("/proc/self");I.mkdir("/proc/self/fd");I.R({R(){var b=I.createNode(a,"fd",16895,73);b.M={X:K.M.X};b.L={lookup(c,d){c=+d;var e=Q(c);c={parent:null,R:{Ya:"fake"},L:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(I.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();I.mb={MEMFS:K};K.Ua=new I.J(44);K.Ua.stack="<generic error, no stack>";for(var Lc=Array(256),Mc=0;256>Mc;++Mc)Lc[Mc]=String.fromCharCode(Mc);
Gb=Lc;
(()=>{let a=Rb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Rb&&c instanceof Rb))return!1;var d=this.K.S.O,e=this.K.P;c.K=c.K;var g=c.K.S.O;for(c=c.K.P;d.W;)e=d.xa(e),d=d.W;for(;g.W;)c=g.xa(c),g=g.W;return d===g&&e===c},clone:function(){this.K.P||Mb(this);if(this.K.wa)return this.K.count.value+=1,this;var c=Pb,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.K;c=c(e.call(d,g,{K:{value:{count:h.count,ta:h.ta,wa:h.wa,P:h.P,S:h.S,V:h.V,Y:h.Y}}}));c.K.count.value+=1;c.K.ta=
!1;return c},["delete"](){this.K.P||Mb(this);if(this.K.ta&&!this.K.wa)throw new T("Object already scheduled for deletion");Ob(this);var c=this.K;--c.count.value;0===c.count.value&&(c.V?c.Y.ma(c.V):c.S.O.ma(c.P));this.K.wa||(this.K.V=void 0,this.K.P=void 0)},isDeleted:function(){return!this.K.P},deleteLater:function(){this.K.P||Mb(this);if(this.K.ta&&!this.K.wa)throw new T("Object already scheduled for deletion");Qb.push(this);this.K.ta=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(jc.prototype,{pb(a){this.Za&&(a=this.Za(a));return a},Sa(a){this.ma?.(a)},ia:8,readValueFromPointer:dc,fromWireType:function(a){function b(){return this.Aa?ic(this.O.qa,{S:this.zb,P:c,Y:this,V:a}):ic(this.O.qa,{S:this,P:a})}var c=this.pb(a);if(!c)return this.Sa(a),null;var d=gc(this.O,c);if(void 0!==d){if(0===d.K.count.value)return d.K.P=c,d.K.V=a,d.clone();d=d.clone();this.Sa(a);return d}d=this.O.nb(c);d=Tb[d];if(!d)return b.call(this);d=this.za?d.jb:d.pointerType;var e=ec(c,this.O,
d.O);return null===e?b.call(this):this.Aa?ic(d.O.qa,{S:d,P:e,Y:this,V:a}):ic(d.O.qa,{S:d,P:e})}});Y.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>Y.length/2-5-wc.length;f.noExitRuntime&&(Ma=f.noExitRuntime);f.preloadPlugins&&(hb=f.preloadPlugins);f.print&&(oa=f.print);f.printErr&&(n=f.printErr);f.wasmBinary&&(pa=f.wasmBinary);f.addRunDependency=Aa;f.removeRunDependency=Ba;f.FS_createPreloadedFile=lb;f.FS_unlink=(...a)=>I.unlink(...a);f.FS_createPath=(...a)=>Bb(...a);
f.FS_createDevice=(...a)=>I.la(...a);f.FS=I;f.FS_createDataFile=(...a)=>kb(...a);f.FS_createLazyFile=(...a)=>Eb(...a);
var Pc={x:function(a,b,c){Na=c;try{var d=Q(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.ka.sb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=E();z[e>>2]=25856;z[e+4>>2]=5;z[e+8>>2]=191;z[e+12>>2]=35387;for(var g=0;32>g;g++)r[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ka.tb)for(e=E(),a=[],g=0;32>g;g++)a.push(r[e+g+17]);return 0;
case 21519:if(!d.tty)return-59;e=E();return z[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return e=E(),I.Ga(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ka.ub&&(g=[24,80],e=E(),y[e>>1]=g[0],y[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof I||"ErrnoError"!==h.name)throw h;return-h.ea}},y:function(a,b,c,d){Na=d;try{b=b?J(t,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?I.cwd():Q(a).path;if(0==e.length)throw new I.J(44);
b=g+"/"+e}var h=d?E():0;return I.open(b,c,h).fd}catch(k){if("undefined"==typeof I||"ErrnoError"!==k.name)throw k;return-k.ea}},z:()=>Ca(""),h:(a,b,c)=>{b=R(b);V(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Fb(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},ia:8,readValueFromPointer:Lb(b,c,-1==b.indexOf("u")),Z:null})},k:(a,b,c,d)=>{b=R(b);V(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,
g){return g?c:d},ia:8,readValueFromPointer:function(e){return this.fromWireType(t[e])},Z:null})},w:(a,b,c,d,e,g,h,k,m,p,l,q,v)=>{l=R(l);g=W(e,g);k&&=W(h,k);p&&=W(m,p);v=W(q,v);var x=Wb(l);Vb(x,function(){pc(`Cannot construct ${l} due to unbound types`,[d])});qc([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var w=u.O;var F=w.qa}else F=Rb.prototype;u=Sb(l,function(...B){if(Object.getPrototypeOf(this)!==M)throw new T(`Use 'new' to construct ${l}`);if(void 0===A.na)throw new T(`${l} has no accessible constructor`);
var bc=A.na[B.length];if(void 0===bc)throw new T(`Tried to invoke ctor of ${l} with invalid number of parameters (${B.length}) - expected (${Object.keys(A.na).toString()}) parameters instead!`);return bc.apply(this,B)});var M=Object.create(F,{constructor:{value:u}});u.prototype=M;var A=new Xb(l,u,M,v,w,g,k,p);if(A.W){var U;(U=A.W).Pa??(U.Pa=[]);A.W.Pa.push(A)}w=new jc(l,A,!0,!1,!1);U=new jc(l+"*",A,!1,!1,!1);F=new jc(l+" const*",A,!1,!0,!1);Tb[a]={pointerType:U,jb:F};kc(x,u);return[w,U,F]})},o:(a,
b,c,d,e,g)=>{var h=rc(b,c);e=W(d,e);qc([],[a],k=>{k=k[0];var m=`constructor ${k.name}`;void 0===k.O.na&&(k.O.na=[]);if(void 0!==k.O.na[b-1])throw new T(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.O.na[b-1]=()=>{pc(`Cannot construct ${k.name} due to unbound types`,h)};qc([],h,p=>{p.splice(1,0,null);k.O.na[b-1]=uc(m,p,null,e,g);return[]});
return[]})},b:(a,b,c,d,e,g,h,k,m)=>{var p=rc(c,d);b=R(b);b=vc(b);g=W(e,g);qc([],[a],l=>{function q(){pc(`Cannot call ${v} due to unbound types`,p)}l=l[0];var v=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&l.O.Ab.push(b);var x=l.O.qa,u=x[b];void 0===u||void 0===u.U&&u.className!==l.name&&u.sa===c-2?(q.sa=c-2,q.className=l.name,x[b]=q):(Ub(x,b,v),x[b].U[c-2]=q);qc([],p,w=>{w=uc(v,w,l,g,h,m);void 0===x[b].U?(w.sa=c-2,x[b]=w):x[b].U[c-2]=w;return[]});return[]})},A:a=>V(a,yc),g:(a,
b,c)=>{b=R(b);V(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,ia:8,readValueFromPointer:zc(b,c),Z:null})},i:(a,b,c,d,e,g,h)=>{var k=rc(b,c);a=R(a);a=vc(a);e=W(d,e);Vb(a,function(){pc(`Cannot call ${a} due to unbound types`,k)},b-1);qc([],k,m=>{m=[m[0],null].concat(m.slice(1));kc(a,uc(a,m,null,e,g,h),b-1);return[]})},c:(a,b,c,d,e)=>{b=R(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};V(a,{name:b,
fromWireType:e,toWireType:h,ia:8,readValueFromPointer:Lb(b,c,0!==d),Z:null})},a:(a,b,c)=>{function d(g){return new e(r.buffer,C[g+4>>2],C[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);V(a,{name:c,fromWireType:d,ia:8,readValueFromPointer:d},{rb:!0})},B:(a,b)=>{b=R(b);V(a,{name:b,fromWireType:function(c){for(var d=C[c>>2],e=c+4,g,h=e,k=0;k<=d;++k){var m=e+k;if(k==d||0==t[m])h=h?J(t,h,m-h):"",void 0===
g?g=h:(g+=String.fromCharCode(0),g+=h),h=m+1}X(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new T("Cannot pass non-string to std::string");var g=e?Xa(d):d.length;var h=Nc(4+g+1),k=h+4;C[h>>2]=g;e?Ya(d,t,k,g+1):t.set(d,k);null!==c&&c.push(X,h);return h},ia:8,readValueFromPointer:dc,Z(c){X(c)}})},d:(a,b,c)=>{c=R(c);if(2===b){var d=Bc;var e=Cc;var g=Dc;var h=k=>ta[k>>1]}else 4===
b&&(d=Ec,e=Fc,g=Gc,h=k=>C[k>>2]);V(a,{name:c,fromWireType:k=>{for(var m=C[k>>2],p,l=k+4,q=0;q<=m;++q){var v=k+4+q*b;if(q==m||0==h(v))l=d(l,v-l),void 0===p?p=l:(p+=String.fromCharCode(0),p+=l),l=v+b}X(k);return p},toWireType:(k,m)=>{if("string"!=typeof m)throw new T(`Cannot pass non-string to C++ string type ${c}`);var p=g(m),l=Nc(4+p+b);C[l>>2]=p/b;e(m,l+4,p+b);null!==k&&k.push(X,l);return l},ia:8,readValueFromPointer:dc,Z(k){X(k)}})},j:a=>{V(a,yc)},l:(a,b)=>{b=R(b);V(a,{Xb:!0,name:b,ia:0,fromWireType:()=>
{},toWireType:()=>{}})},q:()=>{Ma=!1;Hc=0},m:xc,n:a=>{9<a&&(Y[a+1]+=1)},e:(a,b)=>{var c=S[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${oc(a)}`,new T(a);a=c;a=a.readValueFromPointer(b);return ac(a)},r:(a,b)=>{Ic[a]&&(clearTimeout(Ic[a].id),delete Ic[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ic[a];Kc(()=>Oc(a,performance.now()))},b);Ic[a]={id:c,cc:b};return 0},s:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);ya();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},f:function(a){try{var b=Q(a);I.close(b);return 0}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return c.ea}},v:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var g,h=b=0;h<c;h++){var k=C[a>>2],m=C[a+4>>2];a+=8;var p=I.read(e,r,k,m,g);if(0>p){var l=-1;break a}b+=p;if(p<m)break;"undefined"!=typeof g&&(g+=p)}l=
b}C[d>>2]=l;return 0}catch(q){if("undefined"==typeof I||"ErrnoError"!==q.name)throw q;return q.ea}},t:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Q(a);I.X(e,b,c);va[d>>3]=BigInt(e.position);e.Ea&&0===b&&0===c&&(e.Ea=null);return 0}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return g.ea}},u:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var g,h=b=0;h<c;h++){var k=C[a>>2],m=C[a+4>>2];a+=8;var p=I.write(e,r,k,m,g);if(0>p){var l=
-1;break a}b+=p;if(p<m)break;"undefined"!=typeof g&&(g+=p)}l=b}C[d>>2]=l;return 0}catch(q){if("undefined"==typeof I||"ErrnoError"!==q.name)throw q;return q.ea}},p:Jc},Z=await (async function(){function a(d){Z=d.exports;qa=Z.C;ya();lc=Z.H;Ba("wasm-instantiate");return Z}Aa("wasm-instantiate");var b={a:Pc};if(f.instantiateWasm)return new Promise(d=>{f.instantiateWasm(b,(e,g)=>{d(a(e,g))})});Da??=f.locateFile?f.locateFile?f.locateFile("thorvg.wasm",ja):ja+"thorvg.wasm":(new URL("thorvg.wasm",
import.meta.url)).href;try{var c=await Ga(b);return a(c.instance)}catch(d){return ba(d),Promise.reject(d)}}()),X=Z.E,Nc=Z.F,nc=Z.G,Oc=Z.I;
function Qc(){function a(){f.calledRun=!0;if(!ra){f.noFSInit||I.Fa||ib();Z.D();I.Xa=!1;aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ja.push(b)}Ia(Ja)}}if(0<D)za=Qc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)La();Ia(Ka);0<D?za=Qc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();Qc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
