var Module = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(fa){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var ha=(a,b)=>{throw b;},ia=import.meta.url,ja="",ka,la;
if(fa){var fs=require("fs"),ma=require("path");ia.startsWith("file:")&&(ja=ma.dirname(require("url").fileURLToPath(ia))+"/");la=a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea){try{ja=(new URL(".",ia)).href}catch{}ea&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ka=async a=>
{if(na(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var oa=console.log.bind(console),n=console.error.bind(console),pa,qa,ra=!1,sa,r,t,ta,ua,va,y,wa,xa,ya,za,na=a=>a.startsWith("file://");
function Aa(){var a=qa.buffer;r=new Int8Array(a);ta=new Int16Array(a);t=new Uint8Array(a);ua=new Uint16Array(a);va=new Int32Array(a);y=new Uint32Array(a);wa=new Float32Array(a);za=new Float64Array(a);xa=new BigInt64Array(a);ya=new BigUint64Array(a)}var B=0,Ba=null;function Ca(){B++;f.monitorRunDependencies?.(B)}function Da(){B--;f.monitorRunDependencies?.(B);if(0==B&&Ba){var a=Ba;Ba=null;a()}}
function Ea(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Fa;async function Ga(a){if(!pa)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==Fa&&pa)a=new Uint8Array(pa);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ha(a,b){try{var c=await Ga(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),Ea(d)}}async function Ia(a){var b=Fa;if(!pa&&"function"==typeof WebAssembly.instantiateStreaming&&!na(b)&&!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return Ha(b,a)}
class Ja{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ka=a=>{for(;0<a.length;)a.shift()(f)},La=[],Ma=[],Na=()=>{var a=f.preRun.shift();Ma.push(a)},Oa=!0,Pa=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Qa,C=a=>{for(var b="";t[a];)b+=Qa[t[a++]];return b},D={},F={},Ra={},G=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}},Sa=a=>{throw new G(a);};
function Ta(a,b,c={}){var d=b.name;if(!a)throw new G(`type "${d}" must have a positive integer typeid pointer`);if(F.hasOwnProperty(a)){if(c.tb)return;throw new G(`Cannot register type '${d}' twice`);}F[a]=b;delete Ra[a];D.hasOwnProperty(a)&&(b=D[a],delete D[a],b.forEach(e=>e()))}function H(a,b,c={}){return Ta(a,b,c)}
var Ua=(a,b,c)=>{switch(b){case 1:return c?d=>r[d]:d=>t[d];case 2:return c?d=>ta[d>>1]:d=>ua[d>>1];case 4:return c?d=>va[d>>2]:d=>y[d>>2];case 8:return c?d=>xa[d>>3]:d=>ya[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Va=a=>{throw new G(a.M.U.R.name+" instance already deleted");},Wa=!1,Xa=()=>{},Ya=a=>{if("undefined"===typeof FinalizationRegistry)return Ya=b=>b,a;Wa=new FinalizationRegistry(b=>{b=b.M;--b.count.value;0===b.count.value&&(b.X?b.$.ma(b.X):b.U.R.ma(b.S))});
Ya=b=>{var c=b.M;c.X&&Wa.register(b,{M:c},b);return b};Xa=b=>{Wa.unregister(b)};return Ya(a)},Za=[];function $a(){}
var ab=(a,b)=>Object.defineProperty(b,"name",{value:a}),bb={},cb=(a,b,c)=>{if(void 0===a[b].W){var d=a[b];a[b]=function(...e){if(!a[b].W.hasOwnProperty(e.length))throw new G(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].W})!`);return a[b].W[e.length].apply(this,e)};a[b].W=[];a[b].W[d.ta]=d}},db=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].W&&void 0!==f[a].W[c])throw new G(`Cannot register public name '${a}' twice`);cb(f,a,a);if(f[a].W.hasOwnProperty(c))throw new G(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].W[c]=b}else f[a]=b,f[a].ta=c},eb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function fb(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.qa=c;this.ma=d;this.Y=e;this.ob=g;this.ya=h;this.lb=k;this.Ab=[]}var gb=(a,b,c)=>{for(;b!==c;){if(!b.ya)throw new G(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ya(a);b=b.Y}return a};
function hb(a,b){if(null===b){if(this.Ha)throw new G(`null is not a valid ${this.name}`);return 0}if(!b.M)throw new G(`Cannot pass "${Pa(b)}" as a ${this.name}`);if(!b.M.S)throw new G(`Cannot pass deleted object as a pointer of type ${this.name}`);return gb(b.M.S,b.M.U.R,this.R)}
function ib(a,b){if(null===b){if(this.Ha)throw new G(`null is not a valid ${this.name}`);if(this.Ca){var c=this.Bb();null!==a&&a.push(this.ma,c);return c}return 0}if(!b||!b.M)throw new G(`Cannot pass "${Pa(b)}" as a ${this.name}`);if(!b.M.S)throw new G(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Ba&&b.M.U.Ba)throw new G(`Cannot convert argument of type ${b.M.$?b.M.$.name:b.M.U.name} to parameter type ${this.name}`);c=gb(b.M.S,b.M.U.R,this.R);if(this.Ca){if(void 0===b.M.X)throw new G("Passing raw pointer to smart pointer is illegal");
switch(this.Db){case 0:if(b.M.$===this)c=b.M.X;else throw new G(`Cannot convert argument of type ${b.M.$?b.M.$.name:b.M.U.name} to parameter type ${this.name}`);break;case 1:c=b.M.X;break;case 2:if(b.M.$===this)c=b.M.X;else{var d=b.clone();c=this.Cb(c,I(()=>d["delete"]()));null!==a&&a.push(this.ma,c)}break;default:throw new G("Unsupporting sharing policy");}}return c}
function jb(a,b){if(null===b){if(this.Ha)throw new G(`null is not a valid ${this.name}`);return 0}if(!b.M)throw new G(`Cannot pass "${Pa(b)}" as a ${this.name}`);if(!b.M.S)throw new G(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.M.U.Ba)throw new G(`Cannot convert argument of type ${b.M.U.name} to parameter type ${this.name}`);return gb(b.M.S,b.M.U.R,this.R)}function kb(a){return this.fromWireType(y[a>>2])}
var lb=(a,b,c)=>{if(b===c)return a;if(void 0===c.Y)return null;a=lb(a,b,c.Y);return null===a?null:c.lb(a)},mb={},nb=(a,b)=>{if(void 0===b)throw new G("ptr should not be undefined");for(;a.Y;)b=a.ya(b),a=a.Y;return mb[b]},ob=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},pb=(a,b)=>{if(!b.U||!b.S)throw new ob("makeClassHandle requires ptr and ptrType");if(!!b.$!==!!b.X)throw new ob("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ya(Object.create(a,
{M:{value:b,writable:!0}}))};function qb(a,b,c,d,e,g,h,k,m,p,l){this.name=a;this.R=b;this.Ha=c;this.Ba=d;this.Ca=e;this.zb=g;this.Db=h;this.$a=k;this.Bb=m;this.Cb=p;this.ma=l;e||void 0!==b.Y?this.toWireType=ib:(this.toWireType=d?hb:jb,this.aa=null)}
var rb=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new ob("Replacing nonexistent public symbol");void 0!==f[a].W&&void 0!==c?f[a].W[c]=b:(f[a]=b,f[a].ta=c)},sb,K=(a,b)=>{a=C(a);var c=sb.get(b);if("function"!=typeof c)throw new G(`unknown function pointer with signature ${a}: ${b}`);return c};class tb extends Error{}
var vb=a=>{a=ub(a);var b=C(a);L(a);return b},wb=(a,b)=>{function c(g){e[g]||F[g]||(Ra[g]?Ra[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new tb(`${a}: `+d.map(vb).join([", "]));},M=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new ob("Mismatched type converter count");for(var m=0;m<a.length;++m)H(a[m],k[m])}a.forEach(k=>Ra[k]=b);var e=Array(b.length),g=[],h=0;b.forEach((k,m)=>{F.hasOwnProperty(k)?e[m]=F[k]:(g.push(k),D.hasOwnProperty(k)||(D[k]=[]),D[k].push(()=>
{e[m]=F[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},xb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(y[b+4*d>>2]);return c},yb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function zb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].aa)return!0;return!1}
function Ab(a,b,c,d,e,g){var h=b.length;if(2>h)throw new G("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=zb(b);c="void"!==b[0].name;d=[a,Sa,d,e,yb,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].aa&&d.push(b[e].aa);m=zb(b);e=b.length-2;var p=[],l=["fn"];k&&l.push("thisWired");for(h=0;h<e;++h)p.push(`arg${h}`),l.push(`arg${h}Wired`);p=p.join(",");l=l.join(",");p=`return function (${p}) {\n`;m&&
(p+="var destructors = [];\n");var q=m?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+=`var thisWired = classParam['toWireType'](${q}, this);\n`);for(h=0;h<e;++h)p+=`var arg${h}Wired = argType${h}['toWireType'](${q}, arg${h});\n`,v.push(`argType${h}`);p+=(c||g?"var rv = ":"")+`invoker(${l});\n`;if(m)p+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].aa&&(p+=`${g}_dtor(${g});\n`,
v.push(`${g}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,u]=[v,p+"}\n"];b=(new Function(...x,u))(...d);return ab(a,b)}
var Bb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Cb=[],N=[],Db=a=>{9<a&&0===--N[a+1]&&(N[a]=void 0,Cb.push(a))},O=a=>{if(!a)throw new G(`Cannot use deleted val. handle = ${a}`);return N[a]},I=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Cb.pop()||N.length;N[b]=a;N[b+1]=1;return b}},Eb={name:"emscripten::val",fromWireType:a=>{var b=O(a);Db(a);return b},toWireType:(a,b)=>I(b),ga:8,readValueFromPointer:kb,aa:null},Fb=
(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(wa[c>>2])};case 8:return function(c){return this.fromWireType(za[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Gb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;
b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ib="undefined"!=typeof TextDecoder?new TextDecoder:void 0,P=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ib)return Ib.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=
String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Jb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Kb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ua[c];)++c;c<<=1;if(32<c-a&&Jb)return Jb.decode(t.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ta[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},
Lb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ta[b>>1]=a.charCodeAt(e),b+=2;ta[b>>1]=0;return b-d},Mb=a=>2*a.length,Nb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=va[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Ob=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);
g=65536+((g&1023)<<10)|h&1023}va[b>>2]=g;b+=4;if(b+4>c)break}va[b>>2]=0;return b-d},Pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Qb=0,Rb=(a,b)=>{var c=F[a];if(void 0===c)throw a=`${b} has unknown type ${vb(a)}`,new G(a);return c},Sb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(y[b>>2]=I(d));return a},Tb=[],Ub={},Vb=a=>{var b=Ub[a];return void 0===b?C(a):b},Wb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Xb=a=>{var b=
Tb.length;Tb.push(a);return b},Yb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Rb(y[b+4*d>>2],`parameter ${d}`);return c},Zb={},$b=a=>{sa=a;Oa||0<Qb||(f.onExit?.(a),ra=!0);ha(a,new Ja(a))},ac=a=>{if(!ra)try{if(a(),!(Oa||0<Qb))try{sa=a=sa,$b(a)}catch(b){b instanceof Ja||"unwind"==b||ha(1,b)}}catch(b){b instanceof Ja||"unwind"==b||ha(1,b)}},bc=()=>{if(fa){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},cc=a=>{(cc=bc())(a)},dc=(a,b)=>{for(var c=0,d=a.length-
1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Q=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=dc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ec=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},R=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],fc=(a,b)=>Q(a+"/"+b),
hc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:S.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=dc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ic=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=hc(a).slice(1);b=hc(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,
b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},jc=[],kc=a=>{var b=Array(Hb(a)+1);a=Gb(a,b,0,b.length);b.length=a;return b},lc=[];function mc(a,b){lc[a]={input:[],output:[],sa:b};nc(a,oc)}
var oc={open(a){var b=lc[a.node.rdev];if(!b)throw new S.L(43);a.tty=b;a.seekable=!1},close(a){a.tty.sa.fsync(a.tty)},fsync(a){a.tty.sa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.sa.Wa)throw new S.L(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.sa.Wa(a.tty)}catch(k){throw new S.L(29);}if(void 0===h&&0===e)throw new S.L(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.sa.La)throw new S.L(60);try{for(var e=0;e<d;e++)a.tty.sa.La(a.tty,
b[c+e])}catch(g){throw new S.L(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},pc={Wa(){a:{if(!jc.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}jc=kc(a)}a=jc.shift()}return a},La(a,b){null===b||10===
b?(oa(P(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(oa(P(a.output)),a.output=[])},Xb(){return{Lb:25856,Nb:5,Kb:191,Mb:35387,Jb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Yb(){return 0},Zb(){return[24,80]}},qc={La(a,b){null===b||10===b?(n(P(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(n(P(a.output)),a.output=[])}},T={ia:null,T(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||S.isFIFO(c))throw new S.L(63);T.ia||(T.ia={dir:{node:{da:T.N.da,fa:T.N.fa,lookup:T.N.lookup,ka:T.N.ka,rename:T.N.rename,unlink:T.N.unlink,rmdir:T.N.rmdir,readdir:T.N.readdir,symlink:T.N.symlink},stream:{Z:T.O.Z}},file:{node:{da:T.N.da,fa:T.N.fa},stream:{Z:T.O.Z,read:T.O.read,write:T.O.write,ra:T.O.ra,wa:T.O.wa}},link:{node:{da:T.N.da,fa:T.N.fa,readlink:T.N.readlink},stream:{}},Qa:{node:{da:T.N.da,fa:T.N.fa},stream:S.jb}});c=S.createNode(a,b,c,d);V(c.mode)?(c.N=T.ia.dir.node,c.O=T.ia.dir.stream,
c.P={}):S.isFile(c.mode)?(c.N=T.ia.file.node,c.O=T.ia.file.stream,c.V=0,c.P=null):40960===(c.mode&61440)?(c.N=T.ia.link.node,c.O=T.ia.link.stream):8192===(c.mode&61440)&&(c.N=T.ia.Qa.node,c.O=T.ia.Qa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.P[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Wb(a){return a.P?a.P.subarray?a.P.subarray(0,a.V):new Uint8Array(a.P):new Uint8Array(0)},N:{da(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
V(a.mode)?b.size=4096:S.isFile(a.mode)?b.size=a.V:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},fa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.V!=b&&(0==b?(a.P=null,a.V=0):(c=a.P,a.P=new Uint8Array(b),c&&a.P.set(c.subarray(0,Math.min(b,a.V))),a.V=b)))},lookup(){throw T.Ua;},ka(a,b,c,d){return T.createNode(a,
b,c,d)},rename(a,b,c){try{var d=W(b,c)}catch(g){}if(d){if(V(a.mode))for(var e in d.P)throw new S.L(55);rc(d)}delete a.parent.P[a.name];b.P[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.P[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=W(a,b),d;for(d in c.P)throw new S.L(55);delete a.P[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.P)]},symlink(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&
61440))throw new S.L(28);return a.link}},O:{read(a,b,c,d,e){var g=a.node.P;if(e>=a.node.V)return 0;a=Math.min(a.node.V-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===r.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.P||a.P.subarray)){if(g)return a.P=b.subarray(c,c+d),a.V=d;if(0===a.V&&0===e)return a.P=b.slice(c,c+d),a.V=d;if(e+d<=a.V)return a.P.set(b.subarray(c,c+d),e),d}g=e+d;var h=
a.P?a.P.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.P,a.P=new Uint8Array(g),0<a.V&&a.P.set(h.subarray(0,a.V),0));if(a.P.subarray&&b.subarray)a.P.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.P[e+g]=b[c+g];a.V=Math.max(a.V,e+d);return d},Z(a,b,c){1===c?b+=a.position:2===c&&S.isFile(a.node.mode)&&(b+=a.node.V);if(0>b)throw new S.L(28);return b},ra(a,b,c,d,e){if(!S.isFile(a.node.mode))throw new S.L(43);a=a.node.P;if(e&2||!a||a.buffer!==r.buffer){d=!0;Ea();
e=void 0;if(!e)throw new S.L(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{S:e,Fb:d}},wa(a,b,c,d){T.O.write(a,b,0,d,c,!1);return 0}}},sc=async a=>{a=await ka(a);return new Uint8Array(a)},tc=[],vc=(a,b,c,d)=>{"undefined"!=typeof Browser&&uc();var e=!1;tc.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},xc=(a,b,c,d,e,g,h,k,m,p)=>{function l(x){function u(w){p?.();k||wc(a,b,w,d,e,m);
g?.();Da(v)}vc(x,q,u,()=>{h?.();Da(v)})||u(x)}var q=b?hc(Q(a+"/"+b)):a,v=`cp ${q}`;Ca(v);"string"==typeof c?sc(c).then(l,h):l(c)},yc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function uc(){var a,b,c;S.Ga=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?S.la("/dev","stdin",a):S.symlink("/dev/tty","/dev/stdin");b?S.la("/dev","stdout",null,b):S.symlink("/dev/tty","/dev/stdout");c?S.la("/dev","stderr",null,c):S.symlink("/dev/tty1","/dev/stderr");S.open("/dev/stdin",0);S.open("/dev/stdout",1);S.open("/dev/stderr",1)}function nc(a,b){S.Ta[a]={O:b}}function V(a){return 16384===(a&61440)}
function W(a,b){var c=V(a.mode)?(c=X(a,"x"))?c:a.N.lookup?0:2:54;if(c)throw new S.L(c);for(c=S.ha[zc(a.id,b)];c;c=c.pa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return S.lookup(a,b)}function rc(a){var b=zc(a.parent.id,a.name);if(S.ha[b]===a)S.ha[b]=a.pa;else for(b=S.ha[b];b;){if(b.pa===a){b.pa=a.pa;break}b=b.pa}}
function wc(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:Ac(a),h=b?Q(a+"/"+b):a);a=yc(d,e);h=S.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}S.chmod(h,a|146);b=S.open(h,577);S.write(b,c,0,c.length,0,g);S.close(b);S.chmod(h,a)}}
function Y(a,b={}){if(!a)throw new S.L(44);b.Aa??(b.Aa=!0);"/"===a.charAt(0)||(a=S.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=S.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=ec(e),S.Ia(d)){a=e+"/"+a.slice(g+1).join("/");continue a}else d=d.parent;else{e=Q(e+"/"+a[g]);try{d=W(d,a[g])}catch(k){if(44===k?.za&&h&&b.xb)return{path:e};throw k;}!d.ea||h&&!b.Aa||(d=d.ea.root);if(40960===(d.mode&61440)&&(!h||b.ba)){if(!d.N.readlink)throw new S.L(52);
d=d.N.readlink(d);"/"===d.charAt(0)||(d=ec(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new S.L(32);}function Ac(a){for(var b;;){if(S.Ia(a))return a=a.T.Za,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function zc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.ha.length}function Bc(a){var b=zc(a.parent.id,a.name);a.pa=S.ha[b];S.ha[b]=a}
function Cc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function X(a,b){if(S.Xa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Dc(a,b){if(!V(a.mode))return 54;try{return W(a,b),20}catch(c){}return X(a,"wx")}
function Ec(a,b,c){try{var d=W(a,b)}catch(e){return e.za}if(a=X(a,"wx"))return a;if(c){if(!V(d.mode))return 54;if(S.Ia(d)||Ac(d)===S.cwd())return 10}else if(V(d.mode))return 31;return 0}function Fc(a,b){if(!a)throw new S.L(b);return a}function Gc(a){a=S.rb(a);if(!a)throw new S.L(8);return a}function Hc(a,b=-1){a=Object.assign(new S.fb,a);if(-1==b)a:{for(b=0;b<=S.gb;b++)if(!S.streams[b])break a;throw new S.L(33);}a.fd=b;return S.streams[b]=a}
function Ic(a,b,c){var d=a?.O.fa;a=d?a:b;d??=b.N.fa;Fc(d,63);d(a,c)}function Jc(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.va)}return b}function Kc(a){var b={Ib:4096,Tb:4096,blocks:1E6,Hb:5E5,Gb:5E5,files:S.Ka,Rb:S.Ka-1,Ub:42,flags:2,bc:255};a.N.bb&&Object.assign(b,a.N.bb(a.T.yb.root));return b}function Lc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return S.ka(a,b|8192,c)}function Mc(a,b,c,d){Ic(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Va:d})}
function Nc(a,b,c){if(V(b.mode))throw new S.L(31);if(!S.isFile(b.mode))throw new S.L(28);var d=X(b,"w");if(d)throw new S.L(d);Ic(a,b,{size:c,timestamp:Date.now()})}function Oc(a,b){a="string"==typeof a?a:Ac(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Q(a+"/"+c);try{S.mkdir(d)}catch(e){if(20!=e.za)throw e;}a=d}}return d}function Pc(a,b,c,d){a="string"==typeof a?a:Ac(a);b=Q(a+"/"+b);return S.create(b,yc(c,d))}
function Qc(a){if(!(a.ub||a.vb||a.link||a.P)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.P=la(a.url),a.V=a.P.length}catch(b){throw new S.L(29);}}}
function Rc(a,b,c,d,e){class g{Fa=!1;ja=[];Ea=void 0;Na=0;Ma=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.Ea(l/this.chunkSize|0)[q]}}hb(l){this.Ea=l}Oa(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),v,x=(v=l.getResponseHeader("Accept-Ranges"))&&"bytes"===v;l=(v=l.getResponseHeader("Content-Encoding"))&&"gzip"===
v;var u=1048576;x||(u=q);var w=this;w.hb(E=>{var J=E*u,z=(E+1)*u-1;z=Math.min(z,q-1);if("undefined"==typeof w.ja[E]){var U=w.ja;if(J>z)throw Error("invalid range ("+J+", "+z+") or no bytes requested!");if(z>q-1)throw Error("only "+q+" bytes available! programmer error!");var A=new XMLHttpRequest;A.open("GET",c,!1);q!==u&&A.setRequestHeader("Range","bytes="+J+"-"+z);A.responseType="arraybuffer";A.overrideMimeType&&A.overrideMimeType("text/plain; charset=x-user-defined");A.send(null);if(!(200<=A.status&&
300>A.status||304===A.status))throw Error("Couldn't load "+c+". Status: "+A.status);J=void 0!==A.response?new Uint8Array(A.response||[]):kc(A.responseText||"");U[E]=J}if("undefined"==typeof w.ja[E])throw Error("doXHR failed!");return w.ja[E]});if(l||!q)u=q=1,u=q=this.Ea(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Na=q;this.Ma=u;this.Fa=!0}get length(){this.Fa||this.Oa();return this.Na}get chunkSize(){this.Fa||this.Oa();return this.Ma}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var m=Pc(a,b,d,e);h?m.P=h:k&&(m.P=null,m.url=k);Object.defineProperties(m,{V:{get:function(){return this.P.length}}});var p={};Object.keys(m.O).forEach(l=>{var q=m.O[l];p[l]=(...v)=>{Qc(m);return q(...v)}});p.read=(l,q,v,x,u)=>{Qc(m);l=l.node.P;if(u>=l.length)q=0;else{x=Math.min(l.length-u,x);if(l.slice)for(var w=
0;w<x;w++)q[v+w]=l[u+w];else for(w=0;w<x;w++)q[v+w]=l.get(u+w);q=x}return q};p.ra=()=>{Qc(m);Ea();throw new S.L(48);};m.O=p;return m}
var S={root:null,va:[],Ta:{},streams:[],Ka:1,ha:null,Ra:"/",Ga:!1,Xa:!0,nb:null,Da:0,ab:{},L:class{name="ErrnoError";constructor(a){this.za=a}},fb:class{ja={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ja.flags}set flags(a){this.ja.flags=a}get position(){return this.ja.position}set position(a){this.ja.position=a}},eb:class{N={};O={};ea=null;constructor(a,b,c,d){a||=this;this.parent=a;this.T=a.T;this.id=S.Ka++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get vb(){return V(this.mode)}get ub(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new S.eb(a,b,c,d);Bc(a);return a},Ia(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},gb:4096,rb:a=>S.streams[a],Qb(a,
b=-1){a=Hc(a,b);a.O?.Pb?.(a);return a},jb:{open(a){a.O=S.pb(a.node.rdev).O;a.O.open?.(a)},Z(){throw new S.L(70);}},Ja:a=>a>>8,$b:a=>a&255,oa:(a,b)=>a<<8|b,pb:a=>S.Ta[a],cb(a,b){function c(h){S.Da--;return b(h)}function d(h){if(h){if(!d.mb)return d.mb=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);S.Da++;1<S.Da&&n(`warning: ${S.Da} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Jc(S.root.T),g=0;e.forEach(h=>{if(!h.type.cb)return d(null);h.type.cb(h,
a,d)})},T(a,b,c){var d="/"===c;if(d&&S.root)throw new S.L(10);if(!d&&c){var e=Y(c,{Aa:!1});c=e.path;e=e.node;if(e.ea)throw new S.L(10);if(!V(e.mode))throw new S.L(54);}b={type:a,yb:b,Za:c,va:[]};a=a.T(b);a.T=b;b.root=a;d?S.root=a:e&&(e.ea=b,e.T&&e.T.va.push(b));return a},fc(a){a=Y(a,{Aa:!1});if(!a.node.ea)throw new S.L(28);a=a.node;var b=a.ea,c=Jc(b);Object.keys(S.ha).forEach(d=>{for(d=S.ha[d];d;){var e=d.pa;c.includes(d.T)&&rc(d);d=e}});a.ea=null;a.T.va.splice(a.T.va.indexOf(b),1)},lookup(a,b){return a.N.lookup(a,
b)},ka(a,b,c){var d=Y(a,{parent:!0}).node;a=R(a);if(!a)throw new S.L(28);if("."===a||".."===a)throw new S.L(20);var e=Dc(d,a);if(e)throw new S.L(e);if(!d.N.ka)throw new S.L(63);return d.N.ka(d,a,b,c)},bb(a){return Kc(Y(a,{ba:!0}).node)},dc(a){return Kc(a.node)},create(a,b=438){return S.ka(a,b&4095|32768,0)},mkdir(a,b=511){return S.ka(a,b&1023|16384,0)},ac(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{S.mkdir(d,b)}catch(g){if(20!=g.za)throw g;}}},symlink(a,
b){if(!hc(a))throw new S.L(44);var c=Y(b,{parent:!0}).node;if(!c)throw new S.L(44);b=R(b);var d=Dc(c,b);if(d)throw new S.L(d);if(!c.N.symlink)throw new S.L(63);return c.N.symlink(c,b,a)},rename(a,b){var c=ec(a),d=ec(b),e=R(a),g=R(b);var h=Y(a,{parent:!0});var k=h.node;h=Y(b,{parent:!0});h=h.node;if(!k||!h)throw new S.L(44);if(k.T!==h.T)throw new S.L(75);var m=W(k,e);a=ic(a,d);if("."!==a.charAt(0))throw new S.L(28);a=ic(b,c);if("."!==a.charAt(0))throw new S.L(55);try{var p=W(h,g)}catch(l){}if(m!==
p){b=V(m.mode);if(e=Ec(k,e,b))throw new S.L(e);if(e=p?Ec(h,g,b):Dc(h,g))throw new S.L(e);if(!k.N.rename)throw new S.L(63);if(m.ea||p&&p.ea)throw new S.L(10);if(h!==k&&(e=X(k,"w")))throw new S.L(e);rc(m);try{k.N.rename(m,h,g),m.parent=h}catch(l){throw l;}finally{Bc(m)}}},rmdir(a){var b=Y(a,{parent:!0}).node;a=R(a);var c=W(b,a),d=Ec(b,a,!0);if(d)throw new S.L(d);if(!b.N.rmdir)throw new S.L(63);if(c.ea)throw new S.L(10);b.N.rmdir(b,a);rc(c)},readdir(a){a=Y(a,{ba:!0}).node;return Fc(a.N.readdir,54)(a)},
unlink(a){var b=Y(a,{parent:!0}).node;if(!b)throw new S.L(44);a=R(a);var c=W(b,a),d=Ec(b,a,!1);if(d)throw new S.L(d);if(!b.N.unlink)throw new S.L(63);if(c.ea)throw new S.L(10);b.N.unlink(b,a);rc(c)},readlink(a){a=Y(a).node;if(!a)throw new S.L(44);if(!a.N.readlink)throw new S.L(28);return a.N.readlink(a)},stat(a,b){a=Y(a,{ba:!b}).node;return Fc(a.N.da,63)(a)},fstat(a){var b=Gc(a);a=b.node;var c=b.O.da;b=c?b:a;c??=a.N.da;Fc(c,63);return c(b)},lstat(a){return S.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
Y(a,{ba:!c}).node:a;Mc(null,a,b,c)},lchmod(a,b){S.chmod(a,b,!0)},fchmod(a,b){a=Gc(a);Mc(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?Y(a,{ba:!d}).node:a;Ic(null,a,{timestamp:Date.now(),Va:d})},lchown(a,b,c){S.chown(a,b,c,!0)},fchown(a){a=Gc(a);Ic(a,a.node,{timestamp:Date.now(),Va:!1})},truncate(a,b){if(0>b)throw new S.L(28);a="string"==typeof a?Y(a,{ba:!0}).node:a;Nc(null,a,b)},Vb(a,b){a=Gc(a);if(0>b||0===(a.flags&2097155))throw new S.L(28);Nc(a,a.node,b)},hc(a,b,c){a=Y(a,{ba:!0}).node;Fc(a.N.fa,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new S.L(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Y(a,{ba:!(b&131072),xb:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new S.L(20);}else{if(e)throw new S.L(31);d=S.ka(a,c|511,0);g=!0}if(!d)throw new S.L(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!V(d.mode))throw new S.L(54);if(!g&&(e=d?40960===(d.mode&61440)?32:V(d.mode)&&("r"!==Cc(b)||b&576)?31:X(d,Cc(b)):44))throw new S.L(e);b&512&&!g&&S.truncate(d,0);b&=-131713;e=Hc({node:d,path:Ac(d),flags:b,seekable:!0,position:0,O:d.O,Eb:[],error:!1});e.O.open&&e.O.open(e);g&&S.chmod(d,c&511);!f.logReadFiles||b&1||a in S.ab||(S.ab[a]=1);return e},close(a){if(null===a.fd)throw new S.L(8);a.sb&&(a.sb=null);try{a.O.close&&a.O.close(a)}catch(b){throw b;}finally{S.streams[a.fd]=null}a.fd=null},
Z(a,b,c){if(null===a.fd)throw new S.L(8);if(!a.seekable||!a.O.Z)throw new S.L(70);if(0!=c&&1!=c&&2!=c)throw new S.L(28);a.position=a.O.Z(a,b,c);a.Eb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new S.L(28);if(null===a.fd)throw new S.L(8);if(1===(a.flags&2097155))throw new S.L(8);if(V(a.node.mode))throw new S.L(31);if(!a.O.read)throw new S.L(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S.L(70);b=a.O.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,
b,c,d,e,g){if(0>d||0>e)throw new S.L(28);if(null===a.fd)throw new S.L(8);if(0===(a.flags&2097155))throw new S.L(8);if(V(a.node.mode))throw new S.L(31);if(!a.O.write)throw new S.L(28);a.seekable&&a.flags&1024&&S.Z(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new S.L(70);b=a.O.write(a,b,c,d,e,g);h||(a.position+=b);return b},ra(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new S.L(2);if(1===(a.flags&2097155))throw new S.L(2);if(!a.O.ra)throw new S.L(43);
if(!b)throw new S.L(28);return a.O.ra(a,b,c,d,e)},wa(a,b,c,d,e){return a.O.wa?a.O.wa(a,b,c,d,e):0},Ya(a,b,c){if(!a.O.Ya)throw new S.L(59);return a.O.Ya(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=S.open(a,b.flags);a=S.stat(a).size;var e=new Uint8Array(a);S.read(d,e,0,a,0);"utf8"===b.encoding?c=P(e):"binary"===b.encoding&&(c=e);S.close(d);return c},writeFile(a,
b,c={}){c.flags=c.flags||577;a=S.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Hb(b)+1);b=Gb(b,d,0,d.length);S.write(a,d,0,b,void 0,c.ib)}else if(ArrayBuffer.isView(b))S.write(a,b,0,b.byteLength,void 0,c.ib);else throw Error("Unsupported data type");S.close(a)},cwd:()=>S.Ra,chdir(a){a=Y(a,{ba:!0});if(null===a.node)throw new S.L(44);if(!V(a.node.mode))throw new S.L(54);var b=X(a.node,"x");if(b)throw new S.L(b);S.Ra=a.path},cc(){S.Ga=!1;for(var a of S.streams)a&&S.close(a)},Sb(a,
b){try{var c=Y(a,{ba:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=Y(a,{parent:!0}),R(a),c=Y(a,{ba:!b}),d=!0,e=c.node}catch(g){}return d?e:null},la(a,b,c,d){a=fc("string"==typeof a?a:Ac(a),b);b=yc(!!c,!!d);var e;(e=S.la).Ja??(e.Ja=64);e=S.oa(S.la.Ja++,0);nc(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,m){for(var p=0,l=0;l<m;l++){try{var q=c()}catch(v){throw new S.L(29);}if(void 0===q&&0===p)throw new S.L(6);if(null===q||void 0===q)break;p++;h[k+l]=q}p&&(g.node.atime=Date.now());
return p},write(g,h,k,m){for(var p=0;p<m;p++)try{d(h[k+p])}catch(l){throw new S.L(29);}m&&(g.node.mtime=g.node.ctime=Date.now());return p}});return Lc(a,b,e)}},Sc=Array(256),Tc=0;for(;256>Tc;++Tc)Sc[Tc]=String.fromCharCode(Tc);Qa=Sc;
(()=>{let a=$a.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof $a&&c instanceof $a))return!1;var d=this.M.U.R,e=this.M.S;c.M=c.M;var g=c.M.U.R;for(c=c.M.S;d.Y;)e=d.ya(e),d=d.Y;for(;g.Y;)c=g.ya(c),g=g.Y;return d===g&&e===c},clone:function(){this.M.S||Va(this);if(this.M.xa)return this.M.count.value+=1,this;var c=Ya,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.M;c=c(e.call(d,g,{M:{value:{count:h.count,ua:h.ua,xa:h.xa,S:h.S,U:h.U,X:h.X,$:h.$}}}));c.M.count.value+=1;c.M.ua=
!1;return c},["delete"](){this.M.S||Va(this);if(this.M.ua&&!this.M.xa)throw new G("Object already scheduled for deletion");Xa(this);var c=this.M;--c.count.value;0===c.count.value&&(c.X?c.$.ma(c.X):c.U.R.ma(c.S));this.M.xa||(this.M.X=void 0,this.M.S=void 0)},isDeleted:function(){return!this.M.S},deleteLater:function(){this.M.S||Va(this);if(this.M.ua&&!this.M.xa)throw new G("Object already scheduled for deletion");Za.push(this);this.M.ua=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(qb.prototype,{qb(a){this.$a&&(a=this.$a(a));return a},Sa(a){this.ma?.(a)},ga:8,readValueFromPointer:kb,fromWireType:function(a){function b(){return this.Ca?pb(this.R.qa,{U:this.zb,S:c,$:this,X:a}):pb(this.R.qa,{U:this,S:a})}var c=this.qb(a);if(!c)return this.Sa(a),null;var d=nb(this.R,c);if(void 0!==d){if(0===d.M.count.value)return d.M.S=c,d.M.X=a,d.clone();d=d.clone();this.Sa(a);return d}d=this.R.ob(c);d=bb[d];if(!d)return b.call(this);d=this.Ba?d.kb:d.pointerType;var e=lb(c,this.R,
d.R);return null===e?b.call(this):this.Ca?pb(d.R.qa,{U:d,S:e,$:this,X:a}):pb(d.R.qa,{U:d,S:e})}});N.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>N.length/2-5-Cb.length;S.Ob=xc;S.ha=Array(4096);S.T(T,{},"/");S.mkdir("/tmp");S.mkdir("/home");S.mkdir("/home/web_user");
(function(){S.mkdir("/dev");nc(S.oa(1,3),{read:()=>0,write:(d,e,g,h)=>h,Z:()=>0});Lc("/dev/null",S.oa(1,3));mc(S.oa(5,0),pc);mc(S.oa(6,0),qc);Lc("/dev/tty",S.oa(5,0));Lc("/dev/tty1",S.oa(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(cc(a),b=a.byteLength);return a[--b]};S.la("/dev","random",c);S.la("/dev","urandom",c);S.mkdir("/dev/shm");S.mkdir("/dev/shm/tmp")})();
(function(){S.mkdir("/proc");var a=S.mkdir("/proc/self");S.mkdir("/proc/self/fd");S.T({T(){var b=S.createNode(a,"fd",16895,73);b.O={Z:T.O.Z};b.N={lookup(c,d){c=+d;var e=Gc(c);c={parent:null,T:{Za:"fake"},N:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(S.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();S.nb={MEMFS:T};T.Ua=new S.L(44);T.Ua.stack="<generic error, no stack>";f.noExitRuntime&&(Oa=f.noExitRuntime);
f.preloadPlugins&&(tc=f.preloadPlugins);f.print&&(oa=f.print);f.printErr&&(n=f.printErr);f.wasmBinary&&(pa=f.wasmBinary);f.addRunDependency=Ca;f.removeRunDependency=Da;f.FS_createPreloadedFile=xc;f.FS_unlink=(...a)=>S.unlink(...a);f.FS_createPath=(...a)=>Oc(...a);f.FS_createDevice=(...a)=>S.la(...a);f.FS=S;f.FS_createDataFile=(...a)=>wc(...a);f.FS_createLazyFile=(...a)=>Rc(...a);
var Wc={u:()=>Ea(""),l:(a,b,c)=>{b=C(b);H(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Pa(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},ga:8,readValueFromPointer:Ua(b,c,-1==b.indexOf("u")),aa:null})},y:(a,b,c,d)=>{b=C(b);H(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},ga:8,readValueFromPointer:function(e){return this.fromWireType(t[e])},aa:null})},w:(a,
b,c,d,e,g,h,k,m,p,l,q,v)=>{l=C(l);g=K(e,g);k&&=K(h,k);p&&=K(m,p);v=K(q,v);var x=eb(l);db(x,function(){wb(`Cannot construct ${l} due to unbound types`,[d])});M([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var w=u.R;var E=w.qa}else E=$a.prototype;u=ab(l,function(...A){if(Object.getPrototypeOf(this)!==J)throw new G(`Use 'new' to construct ${l}`);if(void 0===z.na)throw new G(`${l} has no accessible constructor`);var gc=z.na[A.length];if(void 0===gc)throw new G(`Tried to invoke ctor of ${l} with invalid number of parameters (${A.length}) - expected (${Object.keys(z.na).toString()}) parameters instead!`);
return gc.apply(this,A)});var J=Object.create(E,{constructor:{value:u}});u.prototype=J;var z=new fb(l,u,J,v,w,g,k,p);if(z.Y){var U;(U=z.Y).Pa??(U.Pa=[]);z.Y.Pa.push(z)}w=new qb(l,z,!0,!1,!1);U=new qb(l+"*",z,!1,!1,!1);E=new qb(l+" const*",z,!1,!0,!1);bb[a]={pointerType:U,kb:E};rb(x,u);return[w,U,E]})},o:(a,b,c,d,e,g)=>{var h=xb(b,c);e=K(d,e);M([],[a],k=>{k=k[0];var m=`constructor ${k.name}`;void 0===k.R.na&&(k.R.na=[]);if(void 0!==k.R.na[b-1])throw new G(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.R.na[b-1]=()=>{wb(`Cannot construct ${k.name} due to unbound types`,h)};M([],h,p=>{p.splice(1,0,null);k.R.na[b-1]=Ab(m,p,null,e,g);return[]});return[]})},b:(a,b,c,d,e,g,h,k,m)=>{var p=xb(c,d);b=C(b);b=Bb(b);g=K(e,g);M([],[a],l=>{function q(){wb(`Cannot call ${v} due to unbound types`,p)}l=l[0];var v=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&l.R.Ab.push(b);
var x=l.R.qa,u=x[b];void 0===u||void 0===u.W&&u.className!==l.name&&u.ta===c-2?(q.ta=c-2,q.className=l.name,x[b]=q):(cb(x,b,v),x[b].W[c-2]=q);M([],p,w=>{w=Ab(v,w,l,g,h,m);void 0===x[b].W?(w.ta=c-2,x[b]=w):x[b].W[c-2]=w;return[]});return[]})},v:a=>H(a,Eb),k:(a,b,c)=>{b=C(b);H(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,ga:8,readValueFromPointer:Fb(b,c),aa:null})},m:(a,b,c,d,e,g,h)=>{var k=xb(b,c);a=C(a);a=Bb(a);e=K(d,e);db(a,function(){wb(`Cannot call ${a} due to unbound types`,k)},b-1);M([],k,
m=>{m=[m[0],null].concat(m.slice(1));rb(a,Ab(a,m,null,e,g,h),b-1);return[]})},c:(a,b,c,d,e)=>{b=C(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};H(a,{name:b,fromWireType:e,toWireType:h,ga:8,readValueFromPointer:Ua(b,c,0!==d),aa:null})},a:(a,b,c)=>{function d(g){return new e(r.buffer,y[g+4>>2],y[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,
BigInt64Array,BigUint64Array][b];c=C(c);H(a,{name:c,fromWireType:d,ga:8,readValueFromPointer:d},{tb:!0})},x:(a,b)=>{b=C(b);H(a,{name:b,fromWireType:function(c){for(var d=y[c>>2],e=c+4,g,h=e,k=0;k<=d;++k){var m=e+k;if(k==d||0==t[m])h=h?P(t,h,m-h):"",void 0===g?g=h:(g+=String.fromCharCode(0),g+=h),h=m+1}L(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new G("Cannot pass non-string to std::string");
var g=e?Hb(d):d.length;var h=Uc(4+g+1),k=h+4;y[h>>2]=g;e?Gb(d,t,k,g+1):t.set(d,k);null!==c&&c.push(L,h);return h},ga:8,readValueFromPointer:kb,aa(c){L(c)}})},f:(a,b,c)=>{c=C(c);if(2===b){var d=Kb;var e=Lb;var g=Mb;var h=k=>ua[k>>1]}else 4===b&&(d=Nb,e=Ob,g=Pb,h=k=>y[k>>2]);H(a,{name:c,fromWireType:k=>{for(var m=y[k>>2],p,l=k+4,q=0;q<=m;++q){var v=k+4+q*b;if(q==m||0==h(v))l=d(l,v-l),void 0===p?p=l:(p+=String.fromCharCode(0),p+=l),l=v+b}L(k);return p},toWireType:(k,m)=>{if("string"!=typeof m)throw new G(`Cannot pass non-string to C++ string type ${c}`);
var p=g(m),l=Uc(4+p+b);y[l>>2]=p/b;e(m,l+4,p+b);null!==k&&k.push(L,l);return l},ga:8,readValueFromPointer:kb,aa(k){L(k)}})},h:a=>{H(a,Eb)},z:(a,b)=>{b=C(b);H(a,{wb:!0,name:b,ga:0,fromWireType:()=>{},toWireType:()=>{}})},r:()=>{Oa=!1;Qb=0},g:(a,b,c)=>{a=O(a);b=Rb(b,"emval::as");return Sb(b,c,a)},n:(a,b,c,d)=>{a=Tb[a];b=O(b);return a(null,b,c,d)},A:(a,b,c,d,e)=>{a=Tb[a];b=O(b);c=Vb(c);return a(b,b[c],d,e)},p:Db,B:a=>{if(0===a)return I(Wb());a=Vb(a);return I(Wb()[a])},i:(a,b,c)=>{b=Yb(a,b);var d=b.shift();
a--;var e="return function (obj, func, destructorsRef, args) {\n",g=0,h=[];0===c&&h.push("obj");for(var k=["retType"],m=[d],p=0;p<a;++p)h.push(`arg${p}`),k.push(`argType${p}`),m.push(b[p]),e+=`  var arg${p} = argType${p}.readValueFromPointer(args${g?"+"+g:""});\n`,g+=b[p].ga;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;d.wb||(k.push("emval_returnValue"),m.push(Sb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");a=(new Function(...k,e+"};\n"))(...m);c=`methodCaller<(${b.map(l=>
l.name).join(", ")}) => ${d.name}>`;return Xb(ab(c,a))},d:(a,b)=>{a=O(a);b=O(b);return I(a[b])},j:a=>{9<a&&(N[a+1]+=1)},C:a=>I(Vb(a)),D:a=>{var b=O(a);yb(b);Db(a)},e:(a,b)=>{a=Rb(a,"_emval_take_value");a=a.readValueFromPointer(b);return I(a)},s:(a,b)=>{Zb[a]&&(clearTimeout(Zb[a].id),delete Zb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Zb[a];ac(()=>Vc(a,performance.now()))},b);Zb[a]={id:c,ec:b};return 0},t:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);Aa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},q:$b},Z=await (async function(){function a(d){Z=d.exports;qa=Z.E;Aa();sb=Z.K;Da("wasm-instantiate");return Z}Ca("wasm-instantiate");var b={a:Wc};if(f.instantiateWasm)return new Promise(d=>{f.instantiateWasm(b,(e,g)=>{d(a(e,g))})});Fa??=f.locateFile?f.locateFile?f.locateFile("thorvg.wasm",
ja):ja+"thorvg.wasm":(new URL("thorvg.wasm",import.meta.url)).href;try{var c=await Ia(b);return a(c.instance)}catch(d){return ba(d),Promise.reject(d)}}()),L=Z.G,Uc=Z.H,ub=Z.I,Vc=Z.J;
function Xc(){function a(){f.calledRun=!0;if(!ra){f.noFSInit||S.Ga||uc();Z.F();S.Xa=!1;aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();La.push(b)}Ka(La)}}if(0<B)Ba=Xc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Na();Ka(Ma);0<B?Ba=Xc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();Xc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
